### ISSUE TITLE
The selected item in the dropdown menu is missing a checkmark icon

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#104]
**Current Behavior:**
The current dev is missing a checkmark icon next to the selected menu item.

**Expected Behavior:**
1. There should be a checkmark icon next to the selected item. See the [design](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1495%3A19722&viewport=378%2C106%2C0.062175203114748&scaling=min-zoom)
2. Please use the [USWDS check icon](https://designsystem.digital.gov/components/icon/) (the icon in the design mocks is a placeholder from Material UI icons).

**Comment by skeeJay** [comment]
@guy-nj Looks like ready for your QA.

**Comment by guy-nj** [comment]
It looks good in the municipality dropdown. Can we have the same style for all dropdowns (legal structure, industry)? How should we structure the tickets in that case? @aloverso

**Comment by guy-nj** [comment]
Per discussion I will create a story for adding checkmark to other dropdown fields.
