### ISSUE TITLE
Bold the matched letters in the search results

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#105]
**Current Behavior:**
Currently we only use the Material UI's default style. The bold letters is missing.

**Expected Behavior:**
Please[ see the design](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1341%3A0&viewport=378%2C106%2C0.062175203114748&scaling=min-zoom) for reference. The matched letters are bold. Might need @aloverso 's suggestion about how to sort the search results.

**Comment by skeeJay** [comment]
@guy-nj Want to take a look?

**Comment by guy-nj** [comment]
It looks good to me!
