### ISSUE TITLE
The selected item in the dropdown menu is missing a checkmark icon

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#106]
**Current Behavior:**
The dropdown menu is missing a checkmark icon next to the selected item.

**Expected Behavior:**
All dropdown fields should have a checkmark next to the selected item as how the municipality dropdown (ticket #104 ) works.

**Comment by skeeJay** [comment]
@guy-nj Can you review?

**Comment by guy-nj** [comment]
LGTM!
