### ISSUE TITLE
As Poppy, I need to see contact information for county clerk on municipality requirements Task screen

### ISSUE THREAD

**Issue by dltinnovate** [newjersey/business.nj.gov#111]
Activities include:

- [Mapping the proper county to the municipality selected in the on-boarding process]
- [Displaying the County Clerk Information: County Name and Clerk Phone Number]
- [Linking out to the County Clerk Website]

County Clerk information can be found in [Air Table.](https://airtable.com/invite/l?inviteId=invBOQXzyIMg9K6Mm&inviteToken=b2f62f141c99f445876c36aa0b4cd3384abcd5bc70e1feee1d514d5a226c9ba6)

**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=65%3A0&viewport=-6601%2C58%2C0.46470877528190613&scaling=min-zoom)

**Comment by aloverso** [comment]
@guy-nj @dltinnovate where on this task screen do we want this displayed?

**Comment by guy-nj** [comment]
I have included the mock in the story description.

**Comment by skeeJay** [comment]
@dltinnovate Can you take a look at this for review?

**Comment by dltinnovate** [comment]
It looks good. I went through and checked several different municipalities and counties. It works as expected.

I did notice a separate bug. When I go back to edit my entry, I have to scroll down to click next on my legal structure, then the next page loads it looks blank. I had to scroll up to see the town entry field.

**Comment by skeeJay** [comment]
Yeah, I added that to the legal structure ticket #33.

**Comment by dltinnovate** [comment]
Got it. I made a bug ticket for it. Let me know if you want me to delete it.
