### ISSUE TITLE
As Poppy, I need to be able to answer a post-onboarding question about construction in a Task screen

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#113]
Activities include:

- [ ]

Task screen: "Get Your Mercantile License If Your Town Requires It"
Question: "Do you plan to do any renovations or construction on your commercial/industrial space? "
Radio Button Answer: "Yes" and "No"
- If no: additional text: "no further action is required."
- If yes, additional text appears: "**Renovation/ Construction and Building Permits:** A Certificate of Occupancy is required by most townships. The certificate is issued after a local inspection to ensure the building meets the requirements for the business you intend to operate. If you plan to do construction, or change the use of your building, you may need a construction permit as well. Some municipalities may require a fire permit and burglar alarm system. Check with your local Building Department."

@guy-nj what do you think should happen if no is selected? Just the additional text doesn't appear?
Guy's answer: We should still say "No action is needed" even if the user selects No. 

**Design**
This design is an early exploration and needs more team discussion.
[Figma prototype (WIP)](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%[…]n-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1)
[Figma file (see section Task: Comply with Local Laws (WIP))](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=0%3A1)

Additional considerations:

- [ ] it should remember my selection for next time

Dev notes:

- [ ] consider making this generic / configurable in the task markdown file instead of hardcoded to a specific task ID

**Comment by Jesslax** [comment]
@skeeJay done. + a design question for Guy.

**Comment by guy-nj** [comment]
We should communicate there is no action needed when the user selects No. We should do the same for the other zoning permit question.

**Comment by Jesslax** [comment]
@guy-nj You think we should add text if no? "Roger that, no further action is required."

**Comment by skeeJay** [comment]
@Jesslax Can you QA?
