### ISSUE TITLE
Add extra space at the bottom of the page so Intercom icon doesn't overlap Next button

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#115]
**Current Behavior:**
The intercom is overlapping the Next button on mobile view.

**Expected Behavior:**
We can add extra space at the bottom of the page so the Next button can be scrolled above the intercom icon.

![intercom-overlap-next](https://user-images.githubusercontent.com/77984966/116261749-f2061900-a745-11eb-9ff5-593bea143e83.png)

**Comment by skeeJay** [comment]
@guy-nj Can you review?

**Comment by guy-nj** [comment]
Looks good to me.
