### ISSUE TITLE
When editing my onboarding information, step 4 appears to load a blank screen.

### ISSUE THREAD

**Issue by dltinnovate** [newjersey/business.nj.gov#116]
**Current Behavior:**
After I've completed the roadmap, I return to edit my onboarding information, after clicking next on Step 3, Step 4 (Location) appears to load a blank page. Users need to scroll up to see the location field.

**Expected Behavior:**

When editing my information, after selecting next on step 3 (Legal Structure) it should load me at the top of Task 4 (Location) so I can see the entry field.

**Steps to Reproduce:**
1. Click Edit Information from the roadmap screen.
2. Click next through Steps 1 through 3.
3. Step 4 loads in a blank area below the input field.

**Comment by skeeJay** [comment]
@dltinnovate Don't think we need a separate ticket for this, I already added it as review item in ticket #33, which was the user story that introduced it and is still in review.
