### ISSUE TITLE
As Poppy, when I click next during onboarding, I should always arrive at the top of the next onboarding screen

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#123]

**Comment by skeeJay** [comment]
Dupe of #33

**Comment by skeeJay** [comment]
Seems to work as I would expect, though @guy-nj would like to get your eyes on this too, just in case you had an idea of some other transition than what we're seeing.

**Comment by guy-nj** [comment]
Looks the bug has been fixed. Looking good!
