### ISSUE TITLE
"Toast" indicator when manually changing Task status

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#124]
As Poppy, I need to ensure my task status has updated in order to feel confident that I am tracking my tasks accurately.

Designs:
- [Desktop](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4820%3A105760)
- [Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4820%3A105766)

Acceptance Criteria:
- Given: i am on desktop or mobile in a task screen
- When: i have successfully updated the status of that task via the dropdown
- Then: a temporary (5-second) snackbar announcing the completion of that task status update appears on my screen (desktop: upper right corner; mobile: top center)

Note:
- Exact placement of toast indicator needs to be tested with users (see #373 )

**Comment by carye3** [comment]
8.25.21 [changes in figma (Desktop)](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4611%3A99023)

**Comment by aloverso** [comment]
@carye3 can you link to the most recent agreed-upon designs (per our design review today) and then remove the needs-design tag?

**Comment by skeeJay** [comment]
@carye3 Seeing this in context and playing with it for a while, I am thinking the bold "Success" label is misleading: it's big and exciting, and indicates accomplishment of something, and kind of feels like it's implying completion of the Task itself, whereas it's a more mundane "the interface's asynchronous update call was completed." The toast also fires when you are merely changing status to "In Progress," to "Completed" just to see what it does, or even back to "Not Started."

I am wondering if, per the [snackbar guidelines](https://material-ui.com/components/snackbars/), a "message only" box is more appropriate for a small "within Task" update like this, without the headline "Success." e.g.;

<img width="874" alt="Screen Shot 2021-09-08 at 8 44 39 AM" src="https://user-images.githubusercontent.com/506096/132511614-d64ca2ea-69bc-441d-a2bc-72488c56d17e.png">

In our case, I think it would mean removing the word "Success," and just retaining the icon and "Your task status has been updated" in a shorter box. This would also be more aligned with messages you see within Gmail when things get minor updates like "Message archived," which feels analogous here. Thoughts? cc @aloverso @mikewolfd

**Comment by skeeJay** [comment]
@carye3 Just wanted to follow up on these notes above, so that we can keep this ticket moving forward. Thoughts on losing the big title? cc @aloverso @mikewolfd @Jesslax

**Comment by carye3** [comment]
@skeeJay removing the word success and just having "Your task status has been updated" sounds good. @aloverso @mikewolfd 
<img width="404" alt="Screen Shot 2021-09-15 at 9 50 07 AM" src="https://user-images.githubusercontent.com/62653834/133445820-364bf24c-c919-46a5-a935-33b5d13307aa.png">

**Comment by skeeJay** [comment]
Still seeing the title on dev currently.

**Comment by aloverso** [comment]
@skeeJay my bad, moved it back to the review column a bit too early. but the new change is in dev now

**Comment by skeeJay** [comment]
Looks good for now. I know we'll be adjusting again per our design review yesterday, but this is good to go to staging now.
