### ISSUE TITLE
As Poppy, I should receive an industry-specific question for Home-Improvement Contractor asking "Are you going to be a home-based business?"

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#130]
Activities include:

- [On Location page of onboarding, under location question]
- [Add the following question/answer if Poppy selects: Home improvement Contractor, All Other Businesses, or E-Commerce]: "Do you plan to be a home-based business?" [Radio Buttons] "Yes" and "No"
- [If they answer "No" include the following tasks: Identify a Lease, Review Local Site Requirements, Sign Your Lease, Comply with local laws and Certificate of Occupancy/Approval]

cc @Jesslax Please expand as needed

**Comment by aloverso** [comment]
@Jesslax I am confused by "Add the following question/answer if Poppy selects: Home improvement Contractor, All Other Businesses, or E-Commerce"

Can you clarify under what circumstances we should ask the home-based business question?

**Comment by Jesslax** [comment]
@aloverso On the onboarding screen, where we ask folks to pick an industry, if one of the industries they select are:  "Home improvement Contractor", "All Other Businesses", or "E-Commerce", then the home-based business question appears. Let me know if that makes sense.

**Comment by aloverso** [comment]
@Jesslax Oooh I see. The "all other businesses" confused me, but you mean specifically if they select that "other"/generic option. Got it.

Followup questions:
- It appears on the Municipality page, right?
- What is the default value? Yes or No?
- Is it correct that for **any** other business type (say, restaurant), we should not show the question, but we *should* show the associated tasks (Identify a Lease, Review Local Site Requirements, etc). Essentially, they can't be a home-based business, so we don't show the question and create the roadmap assuming they said "no"

**Comment by Jesslax** [comment]
@aloverso 

All good!
1) Yes, it should go under the select your location question
2) Can we not have a default value, that way we ensure people see it and select one? If we must have a default, let's default with yes, that will be more common.
3) 100%, good question

**Comment by aloverso** [comment]
@Jesslax So my question regarding the default is "what do we want them to see on the roadmap if they don't select one of the two options"?

If that answer is "they have to select one or the other", then we have to either:
1. pick a default and then let them change it. this guarantees one will be selected
2. not have a default and show an error if they try to advance without selecting

If we want to do option2, that's totally fine. In that case, I'll add a default for now and change that when we add error handling on the form, if that's ok

**Comment by Jesslax** [comment]
@aloverso thanks for explaining, that makes sense.

Adding @skeeJay @guy-nj Because 1) I know we wanted to avoid error messages and 2) if we do an error message it needs to be designed. What do you all think?
I was suggesting that the home-based business question not have a default selection to ensure that people see it and make a choice. But with Anne's point above, I wanted to see what you two thought.

**Comment by skeeJay** [comment]
"Avoid error messages" is a fair way to get us to an MVP fast, but it's not really a valid mentality for UX design. Intentional approaches could be "give the user a totally blank slate" or "encourage a quick choice and be forgiving about changing it later." We have so far been leaning toward the latter as an approach. For consistency, I'd suggest we stick with that; thus, I'd vote for having a default selected.

**Comment by skeeJay** [comment]
@Jesslax @aloverso "Avoid error messages" is a fair way to get us to an MVP fast, but it's not really a valid mentality for UX design. Intentional approaches could be "give the user a totally blank slate" or "encourage a quick choice and be forgiving about changing it later." We have so far been leaning toward the latter as an approach. For consistency, I'd suggest we stick with that; thus, I'd vote for having a default selected.

**Comment by Jesslax** [comment]
@skeeJay @aloverso makes sense. So there's our answer. I'd make the default 'yes', I believe that will be the more frequent selection.

**Comment by aloverso** [comment]
@Jesslax oh wait, the default is "yes" to home-based business? I must have misread that, or assumed. Is it really more common to be home-based than to have a location?

**Comment by skeeJay** [comment]
Okay, so @Jesslax I think this one is yours to QA. Looks like it functions to me.

**Comment by skeeJay** [comment]
@Jesslax Back to you again.

**Comment by Jesslax** [comment]
@skeeJay @aloverso just checked, looks good. Thanks!
