### ISSUE TITLE
Dev/des May 6

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#131]
- [x] Contextual info link line height is 1.15 but should be 1.6 (default Body text)
- [x] Industry dropdown title and description alignment
- [x] Vertically center aligned leftnav roadmap’s step number, title, and arrow.
- [x] Hover style of contextual info links

**Comment by skeeJay** [comment]
All you @guy-nj .

**Comment by guy-nj** [comment]
All look good. Moving this to Ready to Staging.
