### ISSUE TITLE
As Poppy, I need to be forced to select a municipality during onboarding

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#138]
- [x] On Step 3 of onboarding, prevent user from proceeding without selecting a Legal Structure
- [x] On Step 4 of onboarding, prevent user from proceeding without selecting a Municipality
- [x] remove error when user goes Back

@skeeJay @Jesslax @guy-nj - What should a task like "comply with local laws" (ones that have the box of municipality-specific info) look like for users who haven't provided their municipality?

**Comment by aloverso** [comment]
@guy-nj I'm not sure that message would be true for all cases? For example, Jess wants to add a link to County Clerk to "Review Local Site Requirements" task, where we currently just say "visit county clerk". The task is still valid regardless of whether they provide the municipality, right? It's just that we don't have enough info on our side yet to give them helpful links.

**Comment by guy-nj** [comment]
@aloverso In that case, the message might be toned down to like this: "Some information might be best tailored to your business without your municipality info." 

@Jesslax I would vote Yes for all 3 suggestions. An iterated version for the 2nd point: show "Edit" next to the municipality which allows the user to change the municipality on the same screen (i.e. a popup modal of municipality dropdown), instead of bringing the user back to the Onboarding steps.

**Comment by guy-nj** [comment]
@dltinnovate @Jesslax That makes sense. 

So the question for now is should we force the user to make a municipality selection? I tend to do so and show an error message on municipality onboarding step if the user doesn't select one.

**Comment by skeeJay** [comment]
I updating the error message text to be a bit more conversational and clearer. It appears from the implementation that the string might be intended as "generic" error message text for every onboarding screen, though AFAICT the municipality screen is the only place it is used. Can you confirm? If so, I'd prefer the error text to be more specific, the way I updated it, as long as it isn't used anywhere else.

**Comment by aloverso** [comment]
at the moment, it's both the Municipality screen and the Legal Structure screen

**Comment by skeeJay** [comment]
Got it. Changing it back to something generic.

**Comment by guy-nj** [comment]
I noticed that the page doesn't scroll back to top when the error message appears. Can we fix that for anywhere the error message applies?

**Comment by aloverso** [comment]
@skeeJay We could have unique messages for each page if that's desired

@guy-nj done, scroll-to-top for error should be live on dev in like 10min

**Comment by guy-nj** [comment]
Thanks. It looks good!
