### ISSUE TITLE
As Poppy, I want to see that my license status is being searched on license Task screen

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#148]
Activities include:

- [ ] Add a loading spinner to the Submit button on the Check Status page for License task

**Comment by skeeJay** [comment]
Looks pretty slick to me. @guy-nj please take a look. The only thing I can see that you might want to look close at is whether the spinner is a little off-center on the button.

**Comment by guy-nj** [comment]
Agreed the spinner seems a little bit towards left in the Submit button. Can we make sure it's vertically and horizontally centered? Otherwise it looks good to me!

**Comment by aloverso** [comment]
@guy-nj we're using the same spinner button as the one on Search Business Names - are they both off-center and in need of adjusting? Or just this new one?

@maitanavarro want to take a look at adjusting the spinner centering slightly?

**Comment by guy-nj** [comment]
The business name search spinner looks fine. It's only the license status "Submit" spinner that needs to be vertically centered. Thanks.

**Comment by skeeJay** [comment]
LGTM.
