### ISSUE TITLE
As Poppy, I need to search live Consumer Affairs data on license Task screen

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#150]
Activities include:
- [x] connect to the real webservice instead of using stub license data

Dev todos:

- [x] increase AWS timeout to a lot (1min? more?)
- [x] find out why the DB query might be taking so long. 

QA to-dos:

- [x] Address Line 1 should ignore all trailing/leading spaces in both input and database when matching
- [x] Address Line 1 should ignore all internal spaces in both input and database when matching
- [x] Address Line 1 should ignore/strip out all non A-Za-z0-9 symbols when matching
- [x] Address Line 1 should ignore case entirely when matching, just like the Name matching
- [x] Address Line 1 should match on `addressLine1*`, just like the Name field does, so that it ignores any text appended to addressLine1 as a suffix in the database. For example, typing `123 Main St` into the form should match `123 Main St, Unit 1C` in the database.
- [x] Fix leading/trailing spaces in business name

**Comment by skeeJay** [comment]
@aloverso Have started QA based on the information you provided. I think as we discussed there will be a lot of tweaks, but I'll start by wondering if some of these are possible:

1. I think it’s right that the name field is not case-sensitive, and I think the address field should not be case-sensitive, too.
2. Name and address should both be insensitive to any number of leading/trailing spaces, and should be insensitive to any number of repeated spaces within the string. In essence, a search of `123 Main St` should match a database record of `  123   Main  St   `
3. I think it’s right that Name matches on `fullName*`, to accommodate random suffixes like LLC and Inc. I think Address Line 1 should also match on `addressLine1*` as well, and that way ignoring the Address Line 2 form field matches the logic of allowing any line 2 text that’s appended to addressLine1 as a suffix. For example, typing `123 Main St` into Address Line 1 should match `123 Main St, Unit 1C` in addressLine1
4. Can we constrain the ZIP Code field to only accept an integer? I believe this can be done with `input type=“number”` and that it’s desirable here. It’s in the usual place of city name, and I actually accidentally typed city name into it multiple times. If I’m getting confused, regular users likely will be too. I think we can easily prevent them from making this mistake to themselves.

**Comment by aloverso** [comment]
@skeeJay These all definitely make sense to me. A few thoughts:

- Trying to think of a way we could account for the businesses with leading spaces as they're stored in the DB... we could look for that specifically as part of our query perhaps?
- For your Item2 here, the easiest thing to do for this would be to take out all the spaces. So `123MainSt` would also match. Is that ok?
- Your point about `addressLine1*` makes sense. Should we at some point revisit using Address Line 2 in matching?
- I'm still confused about the existence of so many NY/PA licenses. Should we shrug it off? Or revisit the greyed-out State field?

**Comment by skeeJay** [comment]
@aloverso :

- Defer to you on whether we can craft a query this way, but it does seem like that would be how to implement it.
- Yes, taking out all spaces is fine, I would err on the side of being most forgiving for a first version and tighten the logic from there.
- Yes, we can talk about using Address Line 2 in the future, but again, I think that's a way to tighten the logic at a later time.
- I would ignore NY/PA licenses for now.
- Does the ZIP Code input field thing make sense?

**Comment by aloverso** [comment]
Makes sense. And yes to zip code, sounds good

**Comment by skeeJay** [comment]
@aloverso You wrote "For your Item2 here, the easiest thing to do for this would be to take out all the spaces. So 123MainSt would also match. Is that ok?" I want to make sure I understand: spaces would be taken out of both the _input_ and the _database entry_ before checking to see if they match, yes? That would be as forgiving as possible, even if there are leading and trailing spaces in the database.

**Comment by aloverso** [comment]
@skeeJay yes exactly. just for comparison purposes, ignore all the spaces in both the input address & the database address

**Comment by skeeJay** [comment]
@aloverso: @guy-nj and I have added some more thoughts to tweaking the matching criteria, as in the ticket description. Notably, we figure that in addition to ignoring all spaces and all letter-case, we should ignore all symbols that aren't letters as well. Let us know if not possible for some reason, or if you have any questions. But we think this is a pretty forgiving matching logic for the user.

**Comment by aloverso** [comment]
@skeeJay that makes sense

anything we want to add here about handling other statuses? particularly, even if we don't yet know what we want to do with them, we should make _some_ fix so that they don't incorrectly display as Pending

**Comment by skeeJay** [comment]
@aloverso I think @guy-nj is figuring out the desired logic for #182, which is also considered beta critical. So I would break that requirement out into the other ticket, and not block this ticket, unless you think there is a reason to fix it before deploying this.

**Comment by aloverso** [comment]
That's fine then. Mostly I was thinking about what's beta-critical, so that sounds fine to me
