### ISSUE TITLE
As Poppy, I need to see a redesigned landing page

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#154]
**Prototype Mocks**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2787%3A6429&viewport=191%2C403%2C0.14422255754470825&scaling=min-zoom)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2870%3A37568&viewport=719%2C733%2C0.10565894842147827&scaling=min-zoom)

**Figma Files**
[Laptop](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=2654%3A0) 
[Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A3970)

**Graphic/Images**
[Images.zip](https://github.com/newjersey/business.nj.gov/files/6656835/Images.zip)
[Wavy background](https://github.com/newjersey/business.nj.gov/files/6671042/Bg-Wavvy.zip) The green is success-lighter (#ECF3EC). I attached all formats. Let me know which one works the best.
[Icons in the 2nd section ](https://github.com/newjersey/business.nj.gov/files/6688659/Icons-Section2.zip)

**User Actions**
As Poppy, 
- [x] I see a short title, description and a call-to-action in the hero area that quickly explains what this website can help me. 
- [x] I see a graphic in the hero area.
- [x] I see several images of business owners that I can relate to in the 2nd section. 
- [x] The copy in the 2nd section provides more information about how this site works and what I should anticipate to engage.
- [x] The 3rd section tells me where I can learn more if I am not starting my business today.
- [ ] "Sign Up" button in "Sing Up for Our Newsletter" opens a modal asking my email to complete the sign up process. Design TBD.
- [x] The bottom of the page shows a legal/liability message that I should be aware of before signup.
- [x] I see Intercom icon sticky at the bottom right corner of my screen.
 
### QA notes

**Dev QA**

- [x] "Editable" copy text on the page
- [ ] CSS classes

**Product/design QA**

- [x] Change legal text
- [x] Hover style on the  buttons in "Not Starting Your Business?" section
- [x] Add spacing between the hero and 2nd section
- [x] Move the Log In button in the hero section

**Comment by aloverso** [comment]
@guy-nj - 

@maitanavarro and I were talking about whether it would be possible to have the "mobile carousel" be a separate story here? In the spirit of what you and I were discussing earlier re story size, there's value in getting a working version on the site sooner and then amending / updating with more complex features. It brings down engineering risk (by preventing long-running feature branches that don't have recent code merged in) and also brings down design risk (because you get to see the landing page live as soon as possible and we can make amends/edits now rather than closer to launch time)

What do you think?

**Comment by guy-nj** [comment]
Just wanted to clarify which scenario is it? @aloverso 

1) The mobile carousel is still a part of MVP and we just want to deploy what we currently have so we can start the QA now. We will ignore the carousel behavior on mobile view and the feature will be deployed soon. Design tweak will not be needed.

2) We need to take the mobile carousel out of MVP scope and we will build it after. Design tweak is needed.

Thanks!

**Comment by aloverso** [comment]
My impression of the ideal Agile workflow would be a mix thereof. Ideally we'd get mobile carousel done before MVP, but the agile mindset is to always have the app in a "release-ready" state and continuously iterate and prioritize. I wouldn't want us to put a ton of work into redesigning around saying "the carousel won't be there" but I also don't want to deploy something that "doesn't work" right now.

**Comment by guy-nj** [comment]
Gotcha. I think in order not to deploy a broken site, we can have the 3 card stacking while the carousel are being developed? I did have [a design exploration](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2851%3A584&viewport=1092%2C1277%2C0.17358911037445068&scaling=min-zoom) but it looked not great so I ended up using the carousel. Will that be the temporary solution for this scenario?

**Comment by aloverso** [comment]
Sure that makes sense! As a temporary working solution yes

**Comment by skeeJay** [comment]
@maitanavarro This is looking pretty great! @guy-nj Please take a look and QA from a design perspective.

Because the design for the replacement footer in #155 is yet to come, I would suggest no further work on the footer. However, @maitanavarro I'm wondering if for demo purposes you can update the disclaimer language above the footer. Could you possibly update it to: `This information is supplied as a guide and is not a substitute for legal or professional advice. It is the responsibility of the business owner to comply with all local, county, and state regulations even if they are not listed here. For no-cost assistance with your business, use the live chat to speak with a Business Advocate based in New Jersey.`

**Comment by guy-nj** [comment]
I have added my notes in Product/design QA section. Feel free to remove "Move the Log In button in the hero section" from this story and only having it in #180.

**Comment by skeeJay** [comment]
@guy-nj ^ QA

**Comment by guy-nj** [comment]
Everything looks good. Should I include the "Log Out" button issue in this story or we should create another story fo it?
<img width="833" alt="Screen Shot 2021-07-09 at 1 35 45 PM" src="https://user-images.githubusercontent.com/77984966/125130408-ea140f00-e0ce-11eb-9f1c-375de6ff575c.png">

**Comment by skeeJay** [comment]
@guy-nj Assuming that there is no "harm" in leaving a "Log Out" button on the logging-in state of the Landing Page, should we just mark this as LGTM?

**Comment by guy-nj** [comment]
Sure. Also per discussion that this issue seems only appearing for the new registered user. For the return user who logs back in, this screen stays for few 1-2 seconds and redirects to the onboarding screen. We can decouple this issue from this story.
