### ISSUE TITLE
As Poppy, I need to see legal language at the bottom of Roadmap screen as well as Landing Page

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#155]
**Design**

The liability/legal message appears at the last section on the Landing Page. On the Roadmap screen, the message sit above the footer and appears in the footer-ish style. We will use the same text on both screens for now.

We are getting approval on final language from Danny, but the current proposal is: "This information is supplied as a guide and is not a substitute for legal or professional advice. It is the responsibility of the business owner to comply with all local, county, and state regulations even if they are not listed here. For no-cost assistance with your business, use the live chat to speak with a Business Advocate based in New Jersey."

This ticket is for the text that sits just above the "Innovation footer" on the two pages above. The Innovation footer sits on all pages, and is defined in #173. These can be implemented separately.

[Landing laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2787%3A6429&viewport=149%2C251%2C0.09799368679523468&scaling=min-zoom)
[Dashboard laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=114%3A24&viewport=149%2C251%2C0.09799368679523468&scaling=min-zoom)
[Landing mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2870%3A37568&viewport=978%2C1072%2C0.17243219912052155&scaling=min-zoom)
[Dashboard mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=503%3A1&viewport=978%2C1072%2C0.17243219912052155&scaling=min-zoom)

**Comment by skeeJay** [comment]
@guy-nj ^ QA

**Comment by guy-nj** [comment]
Looks good!

**Comment by aloverso** [comment]
@maitanavarro @guy-nj I just noticed that on a wide screen, the legal-text footer expands beyond the width of the rest of the page. Should we adjust that to keep it within the same margins as the rest of the content?

![image](https://user-images.githubusercontent.com/6563663/125663610-55e7919b-3950-4dfc-a424-229ac9f2a1a2.png)

**Comment by guy-nj** [comment]
@aloverso Good catch. The text should be contained in 960px width (or whatever width the body content is using).

**Comment by maitanavarro** [comment]
Sounds good! I can adjust that
