### ISSUE TITLE
As Poppy, I need to see a "beta bar" across the site asking for feedback

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#156]
**Design**
It appears below the State Header across all pages.
[Web](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2787%3A6429&viewport=149%2C251%2C0.09799368679523468&scaling=min-zoom)
[Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A3970)

**Changes:**
It is always visible on the site (no option to close out of it)

**QA:**
- [x] Please linkify `Let us know what you think!` and link it to https://forms.business.nj.gov/feedback/ [does not exist yet], should match styling in design with an appropriate hover state, and should open a new window when you click the link.
- [x] Apply the [Links component](https://newjersey.github.io/njwds/components/detail/links.html) to the text link "Let us know what you think" and make the font size 0.8 rem - per discussion with @guy-nj and @maitanavarro

**Comment by aloverso** [comment]
@skeeJay @guy-nj This had a link in it, if i recall. where does that link to?

**Comment by skeeJay** [comment]
@aloverso I haven't seen the latest designs myself yet, so this is blocked until @guy-nj is able to attach them. But I suspect the link will go to a JotForm that we need to set up as a separate user story. We can either consider this blocked by that or otherwise just put in a dummy link for the time being.

**Comment by skeeJay** [comment]
@guy-nj ^ QA

**Comment by guy-nj** [comment]
Are we decoupling the Jotform linking from this story? Otherwise everything looks good.

**Comment by skeeJay** [comment]
@guy-nj @Jesslax We should link to a URL now that we will drop a jotform on later. http://forms.business.nj.gov/beta-feedback or something like that… let me know what URL you prefer.

**Comment by skeeJay** [comment]
@maitanavarro Added a linkification to the description tab, please let us know if this is doable as part of the ticket or if we really need a new user story for it.

**Comment by maitanavarro** [comment]
Sounds good! This should be doable as part of the ticket

**Comment by skeeJay** [comment]
@maitanavarro Added a QA item to bring this further into line with the design: specifically on the link, font-weight, text-decoration, and adding an underline on hover. @guy-nj Please take a look as well from a design perspective to see if I am missing any design QA.

**Comment by guy-nj** [comment]
@skeeJay Maita and I have agreed on using the current [NJDS text link component](https://newjersey.github.io/njwds/components/detail/links.html) which is regular font weight with the underline. I will update your QA note above.

**Comment by guy-nj** [comment]
@skeeJay Good point. We need to hide all underlines for the footer links. Will add the note in the story.

**Comment by skeeJay** [comment]
@guy-nj You should define a hover state, too, ideally. Color change or the underline appearing, something like that.

**Comment by guy-nj** [comment]
Yes there is a defined hover state in the [Links component](https://newjersey.github.io/njwds/components/detail/links.html).

**Comment by skeeJay** [comment]
LGTM, @guy-nj can you give it another look and see if we can move to Ready to Deploy to Staging?

**Comment by guy-nj** [comment]
Looks good to me. Move to Ready to Deploy to Staging.
