### ISSUE TITLE
As Poppy, I need to see an error notification across the Dashboard experience when an API call fails

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#157]
**Design**
[Web & Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=2611%3A31634)

The design includes the regular page, 2-column page, with tab, and mobile scenarios.

**Comment by guy-nj** [comment]
I am thinking to show whatever content is available with an error message like "The page content might not be complete due to a connection error." (copy TBD) Do you think that would be a good-enough solution? @skeeJay

Question: does the mini-roadmap need to reload in every task screen? The reason I ask is to consider if the error message should be the full width (960px) or in the right column.

**Comment by skeeJay** [comment]
@guy-nj I'm not sure I understand the specific situation you're describing. This is when you click a Task on the Roadmap and the API call fails? In that situation, I think I would show the error message on the Roadmap screen, not necessarily still take the user to the Task screen with "wrong" information.

**Comment by guy-nj** [comment]
My question was when clicking another task from the mini-roadmap on a task screen. But @skeeJay's solution works in this scenario too. The user should stay and see the error message on the current page.

**Comment by aloverso** [comment]
@skeeJay I think my comment above describes the situation, in which loading user data on a task page might fail, and what might or might not load based on that.

@guy-nj to answer your question, we do in fact cache the user data, so if the API call has succeeded in the past, we _would_ be able to show a mini-roadmap. However, all of these pages can be refreshed/reloaded/visited directly by URL, so there _is_ always a chance that someone might end up on a task screen and we are unable to know their user data (and therefore, their mini-roadmap, their task progress, and/or internal task text changes)

**Comment by aloverso** [comment]
@skeeJay this is complete, but pretty hard to QA because you don't get to see the errors unless something is wrong. maybe we could QA by hopping on a call so I can screenshare the local version, where I have control of turning the API on/off?

**Comment by skeeJay** [comment]
@aloverso Feel free to move to Deploy to Staging when you've made that small tweak.

**Comment by aloverso** [comment]
@skeeJay which tweak? sorry

**Comment by skeeJay** [comment]
@aloverso I think it was moving the error message on the name search Task screen higher up to be consistent with the error message on the licensing Task screen, per @guy-nj 's suggestion.

**Comment by aloverso** [comment]
Right! sorry I forgot, will do
