### ISSUE TITLE
As Poppy, I need to NOT see B-Corp as an option on the "Legal Structure" onboarding screen

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#163]
Activities include:

- [x] Remove B-Corp as an option from the "Legal Structure" onboarding screen

**Comment by skeeJay** [comment]
@Jesslax Just clarified that this refers to "Legal Structure" onboarding screen.

**Comment by skeeJay** [comment]
@Jesslax can you QA?

**Comment by Jesslax** [comment]
@skeeJay looks good to me!
