### ISSUE TITLE
Design: A business should be able to see all their onboarding selections (e.g., "home-based business") in the gray box on the Roadmap page

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#164]
Users currently have no way to remember/check if their current Roadmap is the result of selecting certain options that are not displayed in the "gray box," such as "home-based business."

Activities include:

- Displaying liquor license decision in roadmap profile (if applicable)
- Displaying home-based business decision in roadmap profile (if applicable)
- As onboarding becomes more complicated, consider ways to make sure the roadmap profile doesn't become too complicated 

Related to #207, #391.

**Comment by skeeJay** [comment]
@carye3 You kind of covered this in your designs this week, yeah?
