### ISSUE TITLE
User Testing: knowing which Tasks are related to a specific Task

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#165]
Activities include:

- [ ] Indicate when one Task is dependent on or related to other task(s) within the Task screen
- [ ] Easily reference/go back and forth between the contents of one Task and its dependent Tasks, perhaps by linking, from the Task screen
- [ ] Explore displaying which Tasks are dependent on one another on the Roadmap itself (as opposed to within the task screen)

Action items:
 - [ ] Jess comes up with some example Tasks
 - [ ] Cary explores some other treatments/designs for user testing

**Comment by aaronvux** [comment]
First review with Cary 8/27.

**Comment by carye3** [comment]
@Jesslax based on testing, i think the in-task dependency banners are sufficient to indicate that a task is dependent on another. (ie: no icons or status labels are needed). Thoughts?

**Comment by Jesslax** [comment]
@carye3 I think you're right. That is a good first iteration and we can continue to monitor observations/needs in future user testing.
