### ISSUE TITLE
Design exploration of motivational animations as Roadmap progress is made/completed

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#166]
Things to explore (not all are necessary, testing and exploration should help us determine the appropriate flourishes to add):

- Animation/celebration after completing a single Task
- Animation/celebration after completing an entire Step
- Animation/celebration/acknowledgement after completing the entire Roadmap, along with potentially more information/encouragement about what to do now that the Roadmap is complete

**Comment by skeeJay** [comment]
@Jesslax Does this seem like it has been accomplished by #417 (completing a Section) or do you think there is more design exploration to be done around motivating/making users feel accomplished? cc @carye3

**Comment by Jesslax** [comment]
@skeeJay This a great first version. We previously talked about acknowledging Poppy for completing 50% or 75% etc, but I don't think we need to go there yet. (I thought the graduation ticket was a re-crafted version of this one.)

**Comment by skeeJay** [comment]
Okay I will leave open in case we someday decide to prioritize further exploration.

**Comment by carye3** [comment]
I'll include some animation specs for #417 @skeeJay
