### ISSUE TITLE
As Poppy, I need to easily identify my industry

### ISSUE THREAD

**Issue by dltinnovate** [newjersey/business.nj.gov#17]
**Design**
[Desktop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1680%3A614&viewport=404%2C-785%2C0.2813967764377594&scaling=min-zoom)
[Mobile ](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1783%3A18591&viewport=-432%2C-1207%2C0.36695781350135803&scaling=min-zoom)

**User Actions**
As Poppy,
1. I see a description under the title "Industry" which explains what I need to do on this page.
2. I see a notification explaining that the customized roadmap is only available for a few industries.
3. I see a dropdown field in which the default text tells me to make a selection from the menu.
4. The description under each industry name helps me understand if my business falls into that industry.
5. I know I have to choose the last option "Some Other Industry" (copy TBD) if I don't see any industry suiting my business.
6. I might see industry related questions appearing below the dropdown when I select some industries (ex: Liquor questions when Restaurant selected)
7. I might see a "Learn more" link below the industry dropdown when some industries selected (ex: Home Contractors)

**Comment by skeeJay** [comment]
@guy-nj @Jesslax Please take a look from your respective perspectives.

@guy-nj One thing that might be a minor bug is that the title of each option is not exactly aligned with the description line for each option… not sure if that's something you want to flag.

**Comment by Jesslax** [comment]
@aloverso Will I be able to change the text in the info box, and the descriptions for each industry?

**Comment by skeeJay** [comment]
Don't think this was meant to be closed.

**Comment by aloverso** [comment]
oops closed the wrong one! thanks

**Comment by skeeJay** [comment]
@aloverso I think Jess had a QA-related question, above. @guy-nj, if you get a chance, please review from a design perspective, including the alignment thing I mentioned.

**Comment by aloverso** [comment]
@Jesslax yes! they're already editable in the same `display-content` folder as usual. let me know if you'd like a tour

**Comment by Jesslax** [comment]
@aloverso Ill try it out first and let you know if I have trouble. thanks! 
My review is all set otherwise.

**Comment by guy-nj** [comment]
@skeeJay The alignment issue should be fixed in the next push. @aloverso and I created a list for this week's QA in this ticket #131 . I will QA and respond there to avoid the redundant email notification.

**Comment by skeeJay** [comment]
@guy-nj @Jesslax Sounds like this is signed off on, marking as ready to deploy.
