### ISSUE TITLE
As Poppy, I should not see a hyphen in "In Progress" Task status tags and options

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#170]
Activities include:

- [ ] Task status dropdown
- [ ] Tag that appears next to Tasks on Roadmap

**Comment by aloverso** [comment]
@skeeJay this is editable, you can make this change.
[Here's the file](https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/TaskProgressLookup.ts)

**Comment by skeeJay** [comment]
Oh cool. Thanks!
