### ISSUE TITLE
Create prod environment in AWS

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#174]

**Comment by aloverso** [comment]
@skeeJay this is done. right now it's just the same as dev & staging, not yet fully connected to boomi or anything. do you want me to do the subdomain story #133 next, or hold off until it's in an actual "good" state (in case someone comes across the dashboard.bnj.gov url by accident or something)

fyi, prod is here right now: https://prod.d1fxpe8xsdfr62.amplifyapp.com/

**Comment by skeeJay** [comment]
I think we should hold off and do #133 as late as possible. We wouldn't want anyone to come across it early, and we have indirectly been promoting the dashboard.business.nj.gov address (like if a stakeholder forgot to type staging). Also, who knows, we may decide on different branding before we get that far.

**Comment by skeeJay** [comment]
Everything I tested seems to work in the production environment as it does in staging.
