### ISSUE TITLE
dev/design june 29

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#176]
- [x] License status (?) tooltip spacing
- [x] License task
  - [x] More space (4 → 8px) between Permit Status and [Clock icon] PENDING: 
  - [x] Tab top/bottom spacing 8 → 12 px
  - [x] Pending icon on status is not blue

**Comment by guy-nj** [comment]
@aloverso I have removed the hover request. It was a fake alert. All done!
