### ISSUE TITLE
As Poppy, I should see a new Task in the Roadmap for certain industries to search other licenses I might need

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#177]
Activities include:

- If poppy selects "another industry" or "e-commerce," display "search-licenses.md" under Step 5.

**Comment by skeeJay** [comment]
@Jesslax Does this need a design?

**Comment by Jesslax** [comment]
@skeeJay. I was not thinking we'd give it a unique design it, but I suppose we could. I could show folks what I am looking to add to see if there is possibility for a design. I thought this would be another regular task screen. It needs to be engineered because there is no .json file that lets me make add ons to all other businesses or e-commerce selections.

**Comment by skeeJay** [comment]
@Jesslax Okay. At minimum, I think you need to attach a spec of what you're envisioning.

**Comment by Jesslax** [comment]
@skeeJay agree if we want it designed. But right now, all I am asking is to be able to add a specific task to the "another industry" and "e-commerce" selection. That task is: https://github.com/newjersey/business.nj.gov/blob/main/web/roadmaps/tasks/search-licenses.md

**Comment by skeeJay** [comment]
Ok, I understand now. Just updating the user story title to make it more specific about implementation for the developer team.

**Comment by aloverso** [comment]
@Jesslax do you want the same task if it's "e-commerce" or if it's "another industry"? Noticed that the task contains e-commerce specific language

**Comment by Jesslax** [comment]
@aloverso Good question. I want it for both, "e-commerce" and "another industry". I need to make copy edits before it goes to staging.

**Comment by skeeJay** [comment]
@Jesslax Feel free to QA.

**Comment by Jesslax** [comment]
@skeeJay @aloverso Looks good!
