### ISSUE TITLE
As Jess, I need to be able to edit the text in the "gray box" profile when a user has not set an industry

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#178]
Activities include:

- When "some other industry" is selected the profile should say "X" instead of "not set"

Dev tasks:

- [ ] instead of having `greyBoxNotSetText` used for all 4 fields, create a new one specifically for Industry so that it can be edited independently

**Comment by skeeJay** [comment]
@Jesslax Did you mean to put this on the engineering Sprint Planning backlog?

**Comment by Jesslax** [comment]
@skeeJay Yes, I asked Anne, and I can't change it myself. When we were reviewing copy, you and I talked about wanting to make this change.

**Comment by skeeJay** [comment]
@Jesslax So the ask is that the particular text string become editable by you going forward, yes? Or do you want them to hardcode a specific message you have drafted?

**Comment by Jesslax** [comment]
@skeeJay that's a good point, probably best if I can edit it going forward.

**Comment by skeeJay** [comment]
@Jesslax I changed what the ticket is called.

**Comment by skeeJay** [comment]
@Jesslax Feel free to QA.

**Comment by Jesslax** [comment]
@skeeJay @aloverso showed me how to change this, looks good. All set.
