### ISSUE TITLE
User flow for all types of Dashboard users

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#179]
1. As a net new user,
I click Get Started on the landing page. Then I see MyNJ to register my user/login account. Then I am brought to the onboarding steps.

2. As a registered user who hasn't finished the MyNJ registration, 
I need to click Get Started on the landing page to start again the MyNJ registration. Then I am brought to the onoarding steps.

3. As a registered user who hasn't finished the onboarding,
I can click Log In on the landing page to continue my onboarding process. After logged in, I am brought to where I was left in the onboarding steps.

4. As a registered user who finished the onboarding,
I can click Log In on the landing page and I am brought to the roadmap page.

@skeeJay @Jesslax @aloverso Any missing scenarios?

**Comment by skeeJay** [comment]
@guy-nj Can you remind us, what ticket or review is this blocking?

**Comment by guy-nj** [comment]
Not really blocking for the current reviews. Since Maita is adding the Log In button on the landing page and we are implementing MyNJ, we need to make sure all user flows being thought through.

**Comment by aloverso** [comment]
This makes sense to me

@guy-nj is there a finalized design in place for @maitanavarro to know how the Login button should be added to the Landing Page?

@skeeJay I think this flow also needs a development story, for "As a newly signed-in/registered user, I want to be taken directly to the onboarding flow". This is different from the current functionality, which takes new users back to the landing page after login.

**Comment by skeeJay** [comment]
User story created as #180.

**Comment by guy-nj** [comment]
I have added the Log In button in the hero section. Please see both laptop and mobile design links above.

**Comment by skeeJay** [comment]
@guy-nj I don't see any links above on this ticket. Are they on another ticket? Can you add the them to #180, which we created as the user story companion to this Drawing Board ticket?

**Comment by guy-nj** [comment]
Sorry I was lost in these 3 tickets. I meant all designs were all updated in #154. 

I have added 'Add "Log In" button in the hero section' in #180 - is there anything missing? @skeeJay

**Comment by skeeJay** [comment]
@guy-nj Okay. I think we just need @aloverso to tell us if this breakdown into these separate tickets, all using the same design, makes sense, or if there are any questions.
