### ISSUE TITLE
User Testing: editing a previously-entered onboarding selection directly/going back from the Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#207]
Activities include:

- [ ]

**Comment by carye3** [comment]
Should this be combined with #97 ?

**Comment by skeeJay** [comment]
@carye3 We have used separate tickets for the design of a feature and the user story/engineering development of the feature, mostly because we have separated research/design and development into to separate boards. In this case, #207 is the design ticket and #97 is the user story for development.
