### ISSUE TITLE
User Testing: Status location in Task Screen

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#208]
Activities include:

- [ ]

**Comment by aaronvux** [comment]
First review 8/24 with Cary.

**Comment by carye3** [comment]
New versions created 8.24: 

- [Roadmap Screen with right-aligned status buttons](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4607%3A97126)
- [Task Screen with header treatment and larger status button](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4608%3A98103)

**Comment by carye3** [comment]
Updated with task status dropdown below task header: https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4716%3A101816

**Comment by skeeJay** [comment]
@carye3 Thanks. This makes the Task screen a little less compact but I suspect might be a lot more findable. Though we had talked about a few options, including putting it above the title, to the left of the title, etc. Is it worth maybe showing all those options to the team at design review, or testing them all with users somehow, to see if one works better than the others? cc @aaronvux

**Comment by carye3** [comment]
An alternative @skeeJay @aaronvux for [above the task header](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4755%3A99761):

![image](https://user-images.githubusercontent.com/62653834/131503989-012f8554-79ba-4ba5-ad48-1195af89b9e0.png)

![image](https://user-images.githubusercontent.com/62653834/131504016-22d22770-7b2f-4bd4-b78e-317074f43ab5.png)

**Comment by skeeJay** [comment]
@carye3 I'd personally against adding more lines and bars to the experience, but I'm happy to hear other opinions at design review. I particularly think it'll get very duplicative when paired with the design on the license status Task screen (below). Though I think it would be really helpful for the design review group to see these options, as well as the plain dropdown to the left of the title, and maybe, also above the title. Could the group see all these alternatives next to each other at design review tomorrow? Do you have thoughts about maybe testing this with some users in a low-fi way?

<img width="979" alt="Screen Shot 2021-08-31 at 8 43 56 AM" src="https://user-images.githubusercontent.com/506096/131505316-fd53f313-10bb-402a-9fb7-814c4ee608af.png">

**Comment by carye3** [comment]
@skeeJay absolutely, will bring this to Design Review. Just sent out a user pipeline discussion for friday as well.

**Comment by carye3** [comment]
@aaronvux can you take a look at the above designs?

**Comment by aaronvux** [comment]
I like the dropdown next to the name without the header bar.  However, I can see how the stand alone bar could be helpful though drawing more attention to the status.  I like the dropdown with borders, maybe we could do that with it to the left of the title?
