### ISSUE TITLE
Design exploration of way to step to next Task (or back to Roadmap) from bottom of Task

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#209]
**Design**
[Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2123%3A5&viewport=-4497%2C42%2C0.32508397102355957&scaling=min-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1)
[Figma file](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4244%3A93748) (see “Next/Prev” component on “Task-Screen” board)

Guy's thoughts/questions for next steps:
1. Hide the task title on the mobile screen?
2. Vertical center or top alignment?

**Comment by aaronvux** [comment]
First review 8/24 with Cary.

**Comment by carye3** [comment]
New versions create 8.24: [Desktop](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4577%3A96111), [Mobile](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4577%3A95484)

**Comment by carye3** [comment]
@skeeJay updated based on your feedback: https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4577%3A96111

**Comment by skeeJay** [comment]
@carye3 Thanks, this reflects what I remember us talking about, and it's very helpful to see it in Figma and be able to play with it. I'm interested to get other's thoughts (@Jesslax @aaronvux @aloverso et al) but I still kind of worry that it makes the bottom of every Task screen the busiest part of the screen now and _always_ draws your eye, instead of mostly just being findable when you get to the bottom. I'm not totally sure how to address that, but I am wondering what it would look like 1) with a lighter outline for the buttons, 2) reducing the height of the buttons, 3) maybe both? Do others think it would be worth seeing some of these styles compared? I'm particularly gun-shy about this design change because it'll affect every single Task screen and the clean, clear, minimalist presentation of the Task screen is I think a major positive factor of the Navigator.

**Comment by carye3** [comment]
[Here is an alternative](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4755%3A100637) to consider: 

![image](https://user-images.githubusercontent.com/62653834/131504794-66ad2a4d-cb36-41d1-90ef-fc07dbb12719.png)

**Comment by skeeJay** [comment]
@carye3 Can you bring all these alternatives to the design review so the team can discuss them side-by-side? We have found it really useful to be able to discuss a v1, v2, v3, etc., in those reviews, to mix and match and see the comparative elements of each at the same time, as a group.

**Comment by carye3** [comment]
Just saw your comment @skeeJay -- will do!

**Comment by skeeJay** [comment]
@carye3 Thanks!

**Comment by carye3** [comment]
@aaronvux can you take a look at the above designs?
