### ISSUE TITLE
Graphic line not extending to appropriate Step

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#211]
Steps to reproduce: 
1. Create a new account
2. Sign in
3. For industry choose any other businesses
4. Select "no" to home-base business
5. Go to roadmap

Dev notes:

- [ ] dont show roadmap page on first load when user has not yet completed onboarding (dont SSG roadmap page)
- [ ] dont use the useeffect hook in useRoadmap, instead have the onboarding trigger it manually

**Comment by skeeJay** [comment]
@aloverso @Jesslax Created this for the bug we talked about, please rename and add Steps to Recreate as needed.

**Comment by aloverso** [comment]
![image](https://user-images.githubusercontent.com/6563663/127217620-2470d0f9-4b2c-4b0d-a172-a102d56a2809.png)
