### ISSUE TITLE
As Poppy, I should see an updated hero graphic in the top section of the Landing Page

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#215]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=2654%3A0&node-id=2787%3A6384&viewport=-3106%2C548%2C0.372473806142807&scaling=min-zoom&starting-point-node-id=2787%3A6384&show-proto-sidebar=1)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2870%3A37568&viewport=5498%2C4293%2C1.1120537519454956&scaling=min-zoom&starting-point-node-id=2870%3A37568)

**Images**
[This zip file](https://github.com/newjersey/business.nj.gov/files/6890025/Hero-image.zip) has PNG and SVG formats. @maitanavarro let me know if SVG works better.

**Design QA**
- [x] Make the graphic larger and move it closer to the text on the left side. @maitanavarro let us know if the background image works.

**Comment by skeeJay** [comment]
@guy-nj Can you QA?

**Comment by guy-nj** [comment]
Checked with @maitanavarro if we can make the graphic bigger and closer to the text on the left side without sacrificing text's width. The potential solution is to have the graphic as background image to be right-aligned in the hero area.

**Comment by skeeJay** [comment]
@guy-nj Feel free to take another look.

**Comment by guy-nj** [comment]
Looking good. Moved to Ready to Deploy to Staging.
