### ISSUE TITLE
Tech/UX: Discuss ways to streamline/clarify myNJ flow

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#216]
Currently the user's profile shows while the onboarding/roadmap screen is loading. Users may find this confusing. What other options do we want to consider (if at all) while the page is loading?

Activities include:

- [ ]

**Comment by carye3** [comment]
Unclear on this one

**Comment by Jesslax** [comment]
@carye3 me too.

**Comment by skeeJay** [comment]
@Jesslax I created this when I closed #212. #212 wasn't a bug, it was expected behavior, but I know you thought the myNJ login process could be improved. The specific user story you wrote isn't possible, but I figured it beared talking about options with @aloverso if you wanted to continue to pursue changes, and that discussion is what this research task is for.

**Comment by Jesslax** [comment]
@skeeJay Thanks for reminding me. Yes, I would still like to discuss this.

**Comment by skeeJay** [comment]
@Jesslax Based on what @aloverso learned today from OIT, I don't know there's low-hanging fruit for improving the login flow. We should probably define what next steps on this would be if it's going in the next sprint. cc @aaronvux

**Comment by Jesslax** [comment]
@aaronvux want to create stories today?
