### ISSUE TITLE
As Poppy, I need to see a checkmark next to completed Tasks in mini-Roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#217]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=309%3A4065&viewport=137%2C85%2C0.30913448333740234&scaling=min-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=488%3A4051&viewport=554%2C604%2C0.6057695150375366&scaling=min-zoom&starting-point-node-id=2870%3A37568) (click burger menu to see the mini-roadmap in the side nav)

**User Actions**
As Poppy,
1. When I mark a task to Completed, I can see a checkmark next to the task in mini-roadmap.
2. I see the circle remaining empty when the task is Not-Started or In-Progress.

**Comment by skeeJay** [comment]
@guy-nj To you for QA.

**Comment by guy-nj** [comment]
LGTM! Moved to RTDTS (Ready to Deploy to Staging)
