### ISSUE TITLE
As Poppy, I need to see nav on Landing Page

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#219]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2787%3A6429&viewport=137%2C85%2C0.30913448333740234&scaling=min-zoom&starting-point-node-id=2787%3A6429&show-proto-sidebar=1)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2870%3A37568&viewport=2107%2C2407%2C0.4136638045310974&scaling=min-zoom&starting-point-node-id=2870%3A37568)
**Assets**
[Navigator logo](https://github.com/newjersey/business.nj.gov/files/6896344/Navigator-logo.zip)
**User Actions**

Acceptance Criteria:
1. I see Navigator branding the first thing in the navigation bar.
2. I see Log In and Register actions on the right side of the navigation bar across laptop and mobile screens.
3. “Register” acts the same as “Get Started” button in the hero area.
4. “Log In” leads the user to MyNJ log-in experience.
5. On mobile screen, [the Navigator nav appears sticky on the top of the screen](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=3995%3A96592&viewport=867%2C1561%2C0.21337182819843292&scaling=min-zoom&starting-point-node-id=2870%3A37568&show-proto-sidebar=1&hide-ui=1) when it gets scrolled out of the screen. The background is white with 90% opacity. The prototype is built in a hacky way in Figma and will need @maitanavarro and @aloverso ’s suggestion on the animation details.
6. There is no sticky nav on desktop screen.

QA:
- [x] On mobile (iPhone 11 Pro Max, iOS 15, Safari), the Log In button is so close to "Navigator" that they look like they are running over each other. Per the design, I think the padding to the right of "Register" and between "Register" and "Log In" needs to decrease on mobile screens to prevent this. Screenshot below.
- [x] The asset for the Business.NJ.gov wordmark seems to get pixelated when it is resized: as seen in the screenshot, it gets a kind of moire pattern that it does not have at full resolution. I see this on multiple browsers and screen sizes, including this mobile screenshot as well as desktop browsers (macOS, Brave Browser/Blink rendering engine). I'm not sure what the solution is, but I think there are ways to provide assets optimized to resize more smoothly.
- [x] Unsure if this is legacy or was introduced with these edits, but certain "centered" elements on the desktop Landing Page do not seem to be "center aligned" with other elements. "Not Starting a New Business?" above the 3 blocks and the horizontal rule below the 3 blocks are not centered with the blocks themselves. Screenshot below.
- [x] We should probably update the Landing page title tag to Business.NJ.gov Navigator to agree with the new graphics.
- [x] Chrome - Mobile: Get Started and Login buttons are stacked instead of side by side.  "Your Business, Your Guide" are on three lines, instead of two.
- [x] Chrome - Mobile: Clicking, "Get Started" form Cancel and Create buttons layout is incorrect.

![IMG_2465](https://user-images.githubusercontent.com/506096/129750036-651e58ef-86d9-436e-bbc5-112e0e17edd6.PNG)

<img width="1197" alt="Screen Shot 2021-08-17 at 1 04 18 PM" src="https://user-images.githubusercontent.com/506096/129770515-de4bb93a-b2f4-4181-8326-ba5a909a19c4.png">

**Comment by skeeJay** [comment]
Added a couple of QA notes to this in the description at the top. @aaronvux would be curious to get your process and thoughts on QAing a ticket like this as well. (A link to the DEV site where issues for QA are deployed is on the [wiki](https://github.com/newjersey/business.nj.gov/wiki).)
