### ISSUE TITLE
As Poppy, I need to see Profile actions consolidated under a dropdown

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#221]
BLOCKED ON #220 (work on after)

**User Actions**
As Poppy,
3. I see a dropdown menu when I hover or click Profile. There are 2 subnav items: myNewJersey Account and Log Out.
4. Clicking myNewJersey Account brings me to my myNerJersey's "My Account" section in a new tab. @aloverso  to confirm URL. 
6. Clicking Log Out logs me out from Navigator and brings me back to the Landing page (@aloverso to confirm the destination page)

Dev Task

- [x]  Perform end-to-end feature testing to ensure navbar works in mobile

**Comment by skeeJay** [comment]
LGTM.
