### ISSUE TITLE
License status tabs look bad on mobile

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#227]
**Current Behavior:**

Looks bad

**Expected Behavior:**

Should look good

**Design**
Always keep the tabs in the same row. It will need to be swipeable when the tabs are longer than the screen width.

**Current Screenshot**
![Image from iOS](https://user-images.githubusercontent.com/6563663/128924888-69cf3100-7da1-4c38-86d0-a92cacb7e01d.png)

**Comment by aloverso** [comment]
@guy-nj feel free to add extra details if you have? or a link to desired mobile design?
@skeeJay feel free to prioritize

**Comment by skeeJay** [comment]
@carye3 Want to QA with a design eye? cc @kmelefsky

**Comment by carye3** [comment]
LGTM -- here's what i see in chrome on iOS: 
![image](https://user-images.githubusercontent.com/62653834/132411472-cd0b6410-16de-4eac-8c78-921e3ec7b27c.png)

**Comment by skeeJay** [comment]
LGTM as well.
