### ISSUE TITLE
As Poppy, I need to see a roadmap for starting a nail salon business

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#24]
Activities include:

- [ ]

**Comment by skeeJay** [comment]
Seems to work well functionality, and I also used the opportunity to test how changing your Industry "remembers" your completed status for shared tasks, which seems to work well. But @Jesslax you should give this a QA as well to finalize and confirm that the result matches your nail salon roadmap requirements.

**Comment by skeeJay** [comment]
Update: @Jesslax doing QA.

**Comment by Jesslax** [comment]
@aloverso @skeeJay Made some small text updates. Two thoughts (not sure if these are other user stories), but some of the links don't link out to an application, but information where they can learn more. So we may want to change what the text on the button. I don't believe I can change at this point. So this might be a new user story - ability to change text in buttons? For some of the links, I'd like to provide additional contextual information. For example, "Check Site Suitability," we link out to a pdf, but I'd like to direct them where in the PDF they need to read, specifically pages XYZ. There is no room in current design for me to do that. I am guessing these are new user stories? If that's the case, we are good to go.

**Comment by aloverso** [comment]
@Jesslax yes, we can definitely make it so that the button text is changeable, we should just make a new story for that

**Comment by skeeJay** [comment]
Created as user story #83. We have a new user to put in our user stories, "Jess," representing the product owner/business experience lead.
