### ISSUE TITLE
As Poppy, I should receive a industry-specific question about a liquor license if I select "Restaurant" industry type

### ISSUE THREAD

**Issue by juliette17innovation** [newjersey/business.nj.gov#26]
Activities include:

- Is extensible to other questions for other industries (i.e, for specific industries like Home-Improvement Contractor, ask "Are you going to be a home-based business?"
- [ Register a Trade Name, Register an EIN, Register for State Taxes ]
- https://docs.google.com/spreadsheets/d/1tfP-KGtxOrKSftZ58B2G4gL740Wzm4mGC4YI5w0tDWo/edit#gid=1437356068

Task screen content includes:
[Add to Step 2]
[Weight it so at bottom of step]
Title: Confirm Liquor License Availability 
Description: If you plan on serving liquor, verify the cost and availability of a liquor license in your area. [I will probably add more text later]
To Complete must have: Address of potential lease 
CTA: Link to County Clerk selected in roadmap

**Comment by aloverso** [comment]
@skeeJay @Jesslax a few questions on this one:
- is there an impact on the roadmap based on the user's answer to the liquor-license question?
- when we say "extensible to other questions", do we mean something specific, or just that it should be easy to do follow-up stories for other questions?

**Comment by skeeJay** [comment]
@aloverso The one example we added for "extensible to other questions" is "Are you going to be a home-based business?" for home-improvement contractor.

@Jesslax will have to let us know the impact of both these questions on the roadmap.

**Comment by aloverso** [comment]
@skeeJay It should be pretty easy to add the other industry-specific question, but since it'll be its own logic and a new piece of data in the app, I think it should be its own story

**Comment by Jesslax** [comment]
@aloverso 

Item 1) I added the text to the note at the top. Let me know if that's what you're looking for/ or if it's better to share it another way. (Pulled text from the original roadmap architecture).
Item 2) Both. For example, we know we want to do another question that is "Do you plan to be a home-based business?" Home improvement contractor, All Other Businesses, and E-Commerce would get this question. If they select "No" we would then add in a few of our existing tasks (no new tasks). That is the only other industry-specific question I know of now. But when we expand to more industries, we will likely have more industry specific questions. So it would be good to be able to add other ones. An industry specific question needs to display based on to their selection of an industry (so they need to link in some way) and then the users answer to that question needs to link up to the addition of certain tasks. Also if a user ends up getting more than one industry-specific question, we need to make sure they layout cleanly, one beneath the other. Let me know if that answers your question/ a call might be easier.

**Comment by aloverso** [comment]
@Jesslax Noticing you said it should link to the County Clerk based on their selected location. What should it do if they did not select a municipality?

**Comment by Jesslax** [comment]
@aloverso Good question. I think it should say "Next Step: Check with your County Clerk" (I'd put this in the what was formerly the destination field).

**Comment by skeeJay** [comment]
@Jesslax Pls take another look with the new roadmap implications Anne committed to dev and see if those things on the Task screens look good to you.

**Comment by Jesslax** [comment]
@skeeJay @aloverso This looks right to me.

**Comment by skeeJay** [comment]
Okay, LGTM then, marking ready to deploy.
