### ISSUE TITLE
As Poppy, I need to see a "generic" roadmap for starting a business, so that I can select "Other" as my business type

### ISSUE THREAD

**Issue by juliette17innovation** [newjersey/business.nj.gov#27]
@aloverso the roadmap for generic is missing the following tasks under step 3: 1) register for an EIN 2) register for tax purposes

-----
Blocked on: need to define generic roadmap

Activities include:

-  https://docs.google.com/spreadsheets/d/1tfP-KGtxOrKSftZ58B2G4gL740Wzm4mGC4YI5w0tDWo/edit#gid=1437356068

**Comment by skeeJay** [comment]
@Jesslax This also is good for product owner QA.

**Comment by skeeJay** [comment]
@aloverso Quick question: is this the roadmap I get when I select blank/"not-set" as the Industry in the input flow?

**Comment by skeeJay** [comment]
Update: @Jesslax updating copy and then closing.
