### ISSUE TITLE
As Poppy, I need to see a roadmap for starting a restaurant (LLC)

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#29]
Activities include:

**Design**
[Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=90%3A4&viewport=-180%2C63%2C0.07508362829685211&scaling=min-zoom)
[Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=90%3A4)

**Comment by aloverso** [comment]
From @guy-nj - roadmap design ![4e9d9e62-025b-4371-b26b-021d292ad40c](https://user-images.githubusercontent.com/6563663/108109080-727e0e80-705f-11eb-86ab-e7e4a4dc5635.jpeg)
