### ISSUE TITLE
As Poppy, with a MyNJ login the self-registration modal should open when redirect

### ISSUE THREAD

**Issue by mikewolfd** [newjersey/business.nj.gov#294]
Replication:

1. A 1st time user with an existing mynj account goes to the navigator
2. They happen to click the login button next to "Get Started"
3. It takes them to mynj, where they login or are logged in, and redirects them back to the navigator with a SAML error
4. Upon Redirect It returns them to the home page
5. Nothing happens, and it still shows the "Log in" buttons

Solution:

4. Upon Redirect, the Navigator will detect the specific SAML error
5. The user is redirected to the home page, with the "Get Started" modal open
6. The mynj onboarding process continues

**Comment by skeeJay** [comment]
@mikewolfd Might need you to show this to me to properly QA.

**Comment by skeeJay** [comment]
I can't recreate this bug anymore, so let's deploy it, and we can create new bug tickets going forward if needed.
