### ISSUE TITLE
As Poppy, I need to easily identify my municipality via intuitive UX in the input flow

### ISSUE THREAD

**Issue by dhcole** [newjersey/business.nj.gov#3]
**Design**
Would need @Jesslax to confirm the final copy.
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1200%3A18451&viewport=413%2C-968%2C0.07534448057413101&scaling=min-zoom&page-id=1200%3A16159)
Mobile (TBD)

**User Actions**
As Poppy,
1. I see a placeholder text in the municipality input field giving me a hint of what should I type in.
2. I see a full list of municipalities in the dropdown when I click the input field before typing anything.
3. When I start typing, I see search results and the matching words are bold in the dropdown. Will need @aloverso 's suggestion on how to sort the search results. For example, is the order in [this mock](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1341%3A0&viewport=413%2C-968%2C0.07534448057413101&scaling=min-zoom&page-id=1200%3A16159) correct?
4.  After selecting a municipality, if I click the field again, I can search again ([see in the design](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1495%3A19722&viewport=413%2C-968%2C0.07534448057413101&scaling=min-zoom&page-id=1200%3A16159)). I see my selected municipality is highlighted with a checkmark in the dropdown (need @aloverso suggestion how to auto-scroll the selected municipality into the visible area). 
5. Material UI component reference TBD

### dev notes

airtable API ref to get municipality: https://airtable.com/appOAYiVZHz6l4xCL/api/docs#javascript/metadata
- [ ] see if we can create a read-only account to access airtable (shared email?)

**Comment by Jesslax** [comment]
@dhcole The municipality question isn't showing up for me in this iteration.

**Comment by skeeJay** [comment]
Updated the description to remove Dave's old notes.

@Jesslax You don't see municipality selection in the two figma links that Guy put in the description?

**Comment by skeeJay** [comment]
@guy-nj for QA.

**Comment by guy-nj** [comment]
It looks good to me!
