### ISSUE TITLE
As Poppy, I should see a design for a post-onboarding question about construction in a Task screen

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#301]
Implementation of design ticket #112.

Activities include:

- [ ]

**Comment by carye3** [comment]
@skeeJay is this not a content task?

**Comment by skeeJay** [comment]
@carye3 The intention was that the current implementation of this get redesigned. Going to delete this user story to avoid further confusion. Let's move that discussion to the design ticket #112.
