### ISSUE TITLE
As Poppy, I want to see feedback that I have navigated to a new page on mini-roadmap mobile

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#304]
**GIVEN** I am on mobile and navigating using the mini-roadmap hamburger
**WHEN** I click on any task
**THEN** the mini-roadmap should close itself automatically to display the new page content

**Comment by aloverso** [comment]
@carye3 wanted to confirm the interaction here. In the acceptance criteria above, I wrote it as "any" task. That is, if I click on the task that I am already on, it should still close, yeah?

**Comment by carye3** [comment]
> @carye3 wanted to confirm the interaction here. In the acceptance criteria above, I wrote it as "any" task. That is, if I click on the task that I am already on, it should still close, yeah?

That sounds good @aloverso

**Comment by skeeJay** [comment]
LGTM.
