### ISSUE TITLE
Add contextual information that explains what is a home-based business, and how your decision will affect the roadmap

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#311]
Address user concern:
 1)Selection would impact funding opportunities 

Actions:
1)Definition of home based business
2)How the selection impacts their roadmap: A)will help you know what permits you may need to open a brick and mortar location, and B) will not impact opportunities for funding at this stage in their process

**Comment by CeciliaRam** [comment]
[contextual info created](https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/contextual-information/home-based%20business)
