### ISSUE TITLE
Research where Poppy can find their entity ID

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#315]
Activities:

- Update entity ID contextual information
- Find an image and of where to find it and add the image to the contextual information

**Comment by skeeJay** [comment]
@Jesslax Can you specify who the user is? "They" is vague.

**Comment by Jesslax** [comment]
@skeeJay done

**Comment by Jesslax** [comment]
@carye3 I got a [sample business formation document](https://drive.google.com/drive/u/0/folders/1w_8Vr9MWr5EiJu8Pe0j1Y4w0u4A7S5r3). Can you add a design on here that helps the user identify where their entity ID # is on this document. The entity ID # is at the top of the page "0459900607." I will then upload this to page to the relevant contextual information.

**Comment by carye3** [comment]
@Jesslax here's the image: 
![Finding your EID](https://user-images.githubusercontent.com/62653834/132908995-f4fbf896-9735-4276-882d-c27dcd5a83f9.jpg)


(in Figma [here](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4925%3A108069))

**Comment by carye3** [comment]
Option 2 @Jesslax  
![Find Your EID 2](https://user-images.githubusercontent.com/62653834/132913096-4620ecfe-0974-445a-8485-b509a381d7e6.jpg)

**Comment by carye3** [comment]
![Find Your EID 2](https://user-images.githubusercontent.com/62653834/132913745-1f481b2a-e6c6-496b-9199-3d506c61ad8c.jpg)
