### ISSUE TITLE
Research In Good Standing

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#316]
Content: We learned from Don that businesses don't get a certificate of good standing when they form their llc, we need to remove that from the roadmap. 

We should add to the contextual information: the benefits - if you’re going to do business in another state, or someone you are seeking financing from may ask for this

Research: We should explore if we want to add that as a separate task.

Design: We also learned a lot of users are getting a request to file for their certificate of good standing in the mail. Don told us this is sort of a scam and we may want to consider adding an alert?

Notes: https://docs.google.com/document/d/1KTsdLXWF52hT8xErMMYRx6CeOAHWna8ZiWHPJ2N_IZc/edit?usp=sharing

**Comment by CeciliaRam** [comment]
[content created](https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/contextual-information/good-standing.md)
