### ISSUE TITLE
User Research: Who is the right user for our current navigator offerings plan or start users?

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#319]
The current roadmap includes both the plan and start user. We should continue to monitor if users find this confusing and how we might want to address this.

**Comment by Jesslax** [comment]
@skeeJay @carye3 I think we can delete this tkt, it gets addressed by adding a plan and start section in the roadmap. What do you think?

**Comment by skeeJay** [comment]
Yeah I would close this, I think it’s is covered by other things in flight.
