### ISSUE TITLE
As Poppy, I need to mark each task as "not started," "started," or "complete" on my roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#32]
Activities include:

- [ ]

Acceptance criteria:

Given I am on the roadmap screen
And I have changed the status of a task 
Then I see a status tag next to each task indicating where I am in the process of that task. The status are: "Not Started", "In Progress", "Completed".

Given I am on the task screen
Then I can change the status of the task from the dropdown on the top right side. The status are: Not Started, In Progress, Completed.

**Comment by skeeJay** [comment]
This seems to function exactly as intended so far to me. @guy-nj do you want to take a look at this from a design perspective as well?

**Comment by guy-nj** [comment]
It looks good. There is a feature that Anne and I agree to create a new story for that. I will do so and relate the ticket to this.

**Comment by skeeJay** [comment]
@aloverso My statuses all reset to "Not Started" at some point. Unsure of the steps to recreate, but curious whether it was a kind of system-wide reset on the db side. Otherwise, I will try to figure out what I did to cause it.
