### ISSUE TITLE
Design: Update Business.NJ.gov with new wordmark

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#320]
-update the header with Guy's new logo

**Comment by carye3** [comment]
Is this a task about consolidating the design systems for Navigator & Biz.nj.gov?

**Comment by carye3** [comment]
Sent to Joe via slack 9.9.21 

Designs at https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4912%3A107964
