### ISSUE TITLE
Research/Design: How can we better elevate the content in the FAQ section of Business.NJ.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#325]
The FAQ section has a lot of information but users do not go there. 
Users said they expected the FAQ section to be more current events - think a new or often used saved reply

Activities include:
- [ ] Discuss feasibility of testing this feature in Webflow with Joe

**Comment by carye3** [comment]
Initial discussion held with Joe, Ce, Jess, and Cary on 9.7.21. Copy being prepared for mockup 9.9.21
