### ISSUE TITLE
As Poppy, I need to understand the different types of business entities when choosing in the input flow

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#33]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1589%3A24&viewport=624%2C-664%2C0.23836949467658997&scaling=min-zoom)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1728%3A0&viewport=624%2C-664%2C0.23836949467658997&scaling=min-zoom)

**User Actions**
As Poppy,
1. I am seeing the top paragraph briefly explaining what I need to do.
2. I am seeing a list of legal structure radio options and I know I need to make a single selection.
3. I see each legal structure has 1-2 sentences of explanation. I can click "Learn more" to get more information about those who are more complicated and hard to fully understand in short sentences.
4. If I click Next without selecting any legal structure, I see [an error message appearing on the top of the page](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=1200%3A16159&node-id=1763%3A18428&viewport=624%2C-664%2C0.23836949467658997&scaling=min-zoom). On desktop screen, the error message appears below "Onboarding Step 3 of N" and above "Legal Structure".

**Review**

- [x] Please adjust ordering of the options to: LLC 1st, then S-Corp, Sole Proprietorship, General Partnership, C-Corp, B-Corp, LP and finally LLP.

**Comment by skeeJay** [comment]
Based on our open-ended discussion earlier this week, this looks sufficient to me continuing on the assumption we have had that we compel the user to choose one during onboarding and let them know that they can change it later. We can of course change these assumptions later, but I think that should probably come after we can put the beta in front of users.

@Jesslax Please take a look at this from a QA perspective. Also, if you get a chance, it might help our framing of our current assumptions to fix the current copy, including getting rid of "you can click unsure" and putting in text about how "you can change this selection later."

**Comment by skeeJay** [comment]
@aloverso I suppose let us know if this bug should be part of the review checklist or a separate ticket like #116.

**Comment by skeeJay** [comment]
@Jesslax Have you gotten a chance to look at this?

**Comment by Jesslax** [comment]
@skeeJay @aloverso I wanted to change the order of the options. I spoke with Don and wanted to put the more popular options up higher. So: LLC 1st, then C-corp, Sole Proprietorship, General Partnership, C-Corp, B-Corp, LP and finally LLP. I didn't see how I could change the order myself. I updated all other text on Friday.

**Comment by skeeJay** [comment]
@Jesslax K thanks, going forward, when QAing, you can put that into the description of the ticket and reapply the "Needs Work" label.

**Comment by Jesslax** [comment]
@skeeJay noted, thanks.

**Comment by aloverso** [comment]
@Jesslax order has been adjusted. I made some changes so that it can be changed in the future. In the [Legal Structure file](https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/LegalStructureLookup.ts) within the rest of the `display-content` folder, you can now adjust the ordering along with the way that Legal Structures are displayed in the app:
