### ISSUE TITLE
Plan for next user testing topics (e.g., income tax)

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#340]
Activities include:

- [x] Identify userbase for prioritized epics
- [x] Discuss user research pipeline sources, tools, & management
- [x] Discuss user testing pipeline sources, tools, & management
- [x] Create spec

Dependency: Data-Driven Design Process

**Comment by carye3** [comment]
Update: initial pipeline discussion held, UX testing methods mtg held, recruiting for Sprint 19 scheduled for friday 9.10.21

**Comment by carye3** [comment]
Both User testing sessions scheduled and planned
