### ISSUE TITLE
User types/personas brain dump

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#341]
Activities include:

- [ ]

**Comment by carye3** [comment]
2 persona meetings held. Created proto-personas and initial sub-persona categories. This is now an artifact featured in recurring mtgs with Jess, V, and Neha, so moving to done. Next meeting scheduled for Sprint 19 week 1 during which Poppy personas will be finalized, and then planned for updates on a quarterly basis.
