### ISSUE TITLE
Discuss data-driven design process

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#342]
Activities include:

- [x] Discussion of our current process for making design decisions, and the data could inform those decisions
- [x] Overview of Lean UX and how its principles can be applied
- [x] Discussion of tools, including user research repository, relationships

**Comment by Jesslax** [comment]
@skeeJay can we add to this identify technology to better manage user research content and relationships?

**Comment by skeeJay** [comment]
@carye3 Should we close this out?
