### ISSUE TITLE
As Poppy, I need to see my current roadmap location on a task screen

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#35]
**Design**
[Desktop Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=309%3A4801&viewport=-2546%2C-772%2C0.20248106122016907&scaling=min-zoom)
[Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=0%3A1)

**User Actions**
As Poppy,
1. I am able to use the roadmap nav on the left side of the page to navigate where I am in the process.
2. I can expand or collapse any step in the left nav.
3. Clicking on a task title brings me that Task's page.

**Mobile/Tablet Experience**
The left nav of mini-roadmap changes to a mobile side-nav when the browser width <770px. 
[Mobile/Tablet Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=497%3A0&viewport=580%2C1039%2C0.303783655166626&scaling=min-zoom)
[Mobile Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A3970)

Acceptance Criteria:

Given Poppy is is on a Task Screen
Then she sees all the other tasks in that step
And she sees all the other steps in the roadmap

When Poppy clicks on one of the other tasks in the list
Then she is navigated to that Task's page

### **Design QA**

1. The mini roadmap (on the left side and mobile sidebar):  

>   - [x] The vertical line in the mini roadmap from 8 to 4px 
>   - [x] Step circle size is 28px; step number 14px; Step title 15px
>   - [x] Step minimum height 80px (so the number circles are not running into each other and the vertical line is always visible)  
>   - [x] Task checkmark circle size 14px; task title 13px

2. - [x] The task title on the right side should be 32px (h2)
3. - [x] The task body text should be 16px (need to set $theme-body-font-size: "sm")
4. - [x] The border color of the right side content is Base-light (#A9AEB1)
5. - [x] In the "Destination: Local Department of Health" box, the border color is Base-lighter (#DCDEE0); the text of the local contact should be 14px
6. - [x] When there is a button in the task content, the button's top spacing is 48px to the end of the content; bottom spacing is 64px to the border if the entire content is larger than the minimum box height.
7. - [x] The mobile burger menu icon should be white
8. - [x] The task title should be also shown in the top nav next to the menu icon (understanding that it would be repeating with the title in the body).
9. - [x] nav sidebar width 320px on mobile

**Comment by guy-nj** [comment]
Mobile mocks are here. Should I include in here or we create another story?
[Mobile Prototype](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A4051&viewport=535%2C365%2C0.25892695784568787&scaling=min-zoom)
[Mobile Figma](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=488%3A3970)

**Comment by skeeJay** [comment]
@guy-nj This is also ready for a design review by you.

**Comment by guy-nj** [comment]
@skeeJay @aloverso I have included the design QA notes into the description. Let me know if any of them is not clear and a visual is needed.

**Comment by skeeJay** [comment]
@guy-nj Just remember to also add the "needs work" label when you add QA notes.

**Comment by skeeJay** [comment]
@guy-nj This is ready for another design QA too.

**Comment by guy-nj** [comment]
The design looks good to me.
