### ISSUE TITLE
Design "toast" indicator for Task screen that Task status has been updated

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#351]
Activities include:

- [ ]

**Comment by carye3** [comment]
This is in progress

**Comment by carye3** [comment]
"Toast" indicator updated, flagged to use this styling with [Material design "snackbar" component](https://material-ui.com/components/snackbars/)

https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4722%3A99757

**Comment by skeeJay** [comment]
@carye3 Thanks for this, very useful to see the snackbar in context. Though I really wonder if the user will realize the toast at the bottom of the screen is related to the action they just did at the top of the screen. Flagging for @aloverso: is the snackbar styling you've experienced before? One alternative that occurs to me is a "floating" action notification like you see in Gmail (screenshot below), which I assume is a Material Design component as well. It could float in the top-left or top-right of the experience, drawing a better visual link with the action the user just performed. cc @aaronvux 

<img width="406" alt="Screen Shot 2021-08-31 at 7 25 55 AM" src="https://user-images.githubusercontent.com/506096/131494807-016447a7-d31e-41b7-9561-ce7b4df3a15d.png">

**Comment by aloverso** [comment]
@skeeJay @carye3 Material UI lets us choose which section of the screen to float the notification in 

See these demos: https://material-ui.com/components/snackbars/#positioned-snackbars

Options are top-left, top-center, top-right, bottom-left, bottom-center, bottom-right - where do you want it?

**Comment by skeeJay** [comment]
@aloverso Thanks. I think locations like top-left, top-center, and top-right are worth seeing design options for.

**Comment by carye3** [comment]
I will bring this to design review @skeeJay
