### ISSUE TITLE
As Jess, I need to reference steps by their number, not ID

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#352]
Follow up from #146 as discussed with Jess

This will make it easier to build/change roadmaps without having to look up a step ID

For example, this should be a valid input:
```
 {
    "step": 5,
    "weight": 8,
    "task": "apply-for-shop-license"
  },
```

**Comment by Jesslax** [comment]
@aloverso Looks great, all set. In the future, want me to move this over?

**Comment by aloverso** [comment]
@Jesslax yep! if it's good, feel free to move over
