### ISSUE TITLE
As Poppy, I need to see the mobile navigation menu close with an animation

### ISSUE THREAD

**Issue by mikewolfd** [newjersey/business.nj.gov#362]
...so that it is visually pleasing

The navigation menu in mobile currently opens with a css animation but does not close with one.

**Comment by skeeJay** [comment]
@mikewolfd If this is intended for sprint 18, moving into the Current Sprint column.

**Comment by skeeJay** [comment]
Out of curiosity, what easing function and timing does this animation have? Feels like we could make it a little faster/springier, but that's one person's opinion. cc @carye3 as well.

**Comment by FarazA22** [comment]
@skeeJay @carye3 The animation is currently set at .5 seconds. The contextual info panel (side bar that appears on the right) can be used for comparison, it has a duration of .3 seconds.

I think it would make sense to use the same duration across both sidebars. 
Note:  Ticket #414 will add the close animation to the contextual info panel.

**Comment by carye3** [comment]
@FarazA22 i vote for the shorter length as well -- .3 for both. I can add that duration to #414

**Comment by FarazA22** [comment]
@skeeJay @carye3 Sounds good, I'll makes the duration updates under #414

**Comment by skeeJay** [comment]
Before signing off on deploying to staging, I'm still curious: what easing function is this animation using? The current one feels linear, but that's obviously just a guess, so I wanted to find out. cc @FarazA22

**Comment by skeeJay** [comment]
We are going with the "ease" animation that is currently on dev, overriding the "ease-in-ease-out" animation currently on staging, so I'm moving this to Ready to Deploy so that we can update staging.
