### ISSUE TITLE
Design/Research: Redesign Business.NJ.gov home page/hero image

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#388]
Problem: Users communicated that landing page is cluttered, and it does not prioritize their attention. Some of the resources they are most interested in are not easy to find. From an editor perspective, we need standard designs for how to handle emergency alerts vs other alerts, and how to slowly transition out of the alerts to make sure users still know where to find resources. 

Activities:
1) Design that allows for alerts around key program updates
2) Design that allows for alerts around State emergencies
3) Design that can transition us out of a banner bar, but still makes content easy for users to find emergency content
4) Landing page that continues to highlight the chat (most used feature)
5) Landing page that removes eliminates underutilized links and buttons
6) Landing page that continues to highlight the search feature
7) Removing underutilized links and buttons. Prioritize sought after content: 
    how to register my business - 4,175
    Folding COVID information into Updates - 2485
    Licensing and certification guide - 1841
    IDA - 1829   
    Starter kits - 1, 333 
    taxes and filings - 931 
    Closing your business -682 
    MWBE/VBE etc - 509
    contracting with the state - 464 
    Funding Programs - a new page we are looking to add in the near future - no data available
8) More inspiring hero image, representing diverse businesses and business owners, not constrained image
9) Optimize SEO 
10) Consider where we might put a link or icon for businesses to reach the navigator tool - while we are not ready to put this on the site yet, you may want to keep in mind.

**Comment by carye3** [comment]
How are we making design decisions here? is this subject to user testing?

**Comment by Jesslax** [comment]
@carye3 The need for this is based on user testing. Users shared that the website was cluttered, and it was difficult to channel their attention/know what resources the website had that would benefit them.  The goal of the second iteration would be to 1) reduce clutter and 2)streamline the number of things they can click out to/prioritizing what they are most looking for. We would want to do user testing of the designs before deploying.
Based on user testing and data analytics, the most sought after content is:
1) how to register my business
2) starter kits
3) taxes and filings
4) contracting with the state
5) MWBE/VBE etc
6) Eventually this financing database we are working on, but for now COVID resources
7) Licensing and certification guide
