### ISSUE TITLE
Production readiness re-evaluation

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#394]
Blocked:

- [x] follow up with myNJ about the xml metadata
- [ ] follow up with JS about prod firewall
-

- [x] Ask JS about "web service security infrastructure platform"
- [x] Ask WAF team about "security monitoring tools"
- [x] Staging WAF
  - [x] Switch staging to navigator domain #395 
  - [x] Talk to WAF team about staging
  - [x] Re-route staging through WAF
  - [x] Change myNJ redirect for staging to the new domain
- [x] Prod WAF
  - [x] Put production on navigator domain #133   
  - [x] Talk to WAF team about prod
  - [x] Re-route prod through WAF
- [ ] firewall followup with JS
  - [x] confirm IP addresses for the firewall 
- [x] change the myNJ configuration for dev/staging
- [ ] myNJ for prod

**Comment by dsueltenfuss** [comment]
Remaining tasks will be handled with #133
