### ISSUE TITLE
Move staging Navigator to staging.navigator.business.nj.gov

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#395]
As a stakeholder like Melanie, I should be able to access the staging Navigator at a URL consistent with the production Navigator, but with "staging" in front of it.

May be blocked by #133, defer to @aloverso and @mikewolfd.

## Notes

- [ ] The "old" staging.dashboard.business.nj.gov should do a 301-style redirect to staging.navigator.business.nj.gov

**Comment by skeeJay** [comment]
@aloverso Can we get any old dashboard URLs to redirect to navigator instead?

**Comment by aloverso** [comment]
@skeeJay Will look into it

**Comment by aloverso** [comment]
@skeeJay done! ready for review

**Comment by skeeJay** [comment]
LGTM
