### ISSUE TITLE
Design: Create design template for B.NJ.gov on how to structure new Pages with more content for discussion

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#401]
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ] Action item: Cary & Ce & Jess mtg discussing content for Plan.
- [ ] Ideas: Accordions and table of contents (latter for mobile where sidebar nav gets stacked)

**Comment by carye3** [comment]
Action item: meet with Ce & Jess discussing content for Plan. 

Ideas: Accordions and table of contents (latter for mobile where sidebar nav gets stacked)

**Comment by dltinnovate** [comment]
Users need easy navigation between pages within each category (Plan, Start, Operate, Grow).
Users need to see a "table of contents" of what information is on each page.

Questions to explore: how deep does the table of contents need to go? Do we include sub-context articles, just major topics, etc.?
