### ISSUE TITLE
Design: Update/create style guide for Business.NJ.gov to match Navigator branding

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#406]
@carye3 if you can add the description here please.

**Comment by Jesslax** [comment]
@carye3 Do you think we can close this? I assume that the new designs you created for the website allow for more consistent branding between the 2 projects. cc @skeeJay

**Comment by carye3** [comment]
@Jesslax sounds good -- this is captured in #737 

we can close @skeeJay
