### ISSUE TITLE
Design/Content: Ensure consistency of style guide across Business.NJ.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#407]
@carye3 if you can update with details

**Comment by skeeJay** [comment]
@carye3 @Jesslax Is this ticket different/unnecessary now as well?

**Comment by Jesslax** [comment]
@skeeJay I think this will happen when we review the built out redesigned website? So I am fine with closing, unless we want to use this tkt to indicate that review.
