### ISSUE TITLE
Webflow: Update B.NJ.gov homepage, all pages with new wordmark

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#408]
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by skeeJay** [comment]
@carye3 @Jesslax Do you want to spot-check this on B.NJ.gov before I close this ticket?

**Comment by Jesslax** [comment]
@skeeJay I checked a handful of pages, looks good to me.

**Comment by carye3** [comment]
There's a jump in size from the homepage to subpages -- just reached out to Joe about it @skeeJay @Jesslax

**Comment by skeeJay** [comment]
@carye3 That’s intended behavior, right? That was the case with the old word mark, and the whole bar is shorter on the other pages. I think that’s consistent with the way it was before.

**Comment by carye3** [comment]
All good -- lets close it @skeeJay
