### ISSUE TITLE
As Fiona, self-registration modal error toasts need to have aria-alerts

### ISSUE THREAD

**Issue by mikewolfd** [newjersey/business.nj.gov#413]

**Comment by skeeJay** [comment]
@mikewolfd @aloverso Can someone let me know how to QA this?

**Comment by skeeJay** [comment]
@mikewolfd So our screen reader tutorial yesterday was prompted by this, but I forgot to even ask specifically about this when we were doing it. So if VoiceOver is on, does this mean the toast should trigger an audio notification that it's appeared?

**Comment by FarazA22** [comment]
@skeeJay When a user tries to create a new account without completing all three text fields or non-matching emails an alert is displayed above the content. If VoiceOver is on, the alert will trigger an audio notification.
