### ISSUE TITLE
Graduation: As Poppy, I need to know that I have reached a significant milestone in my business roadmap

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#417]
As poppy, i need to know that i have reached a significant milestone when i have completed necessary tasks for a stage of my business (eg "Plan" or "Start")

#### Design

[Graduation Snackbar](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5295%3A130287)
![image](https://user-images.githubusercontent.com/62653834/134411280-ca0153f4-ac9e-4f2e-90ce-ada5ec1785da.png)

[Graduation Modal](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5139%3A119342)
![image](https://user-images.githubusercontent.com/62653834/134411243-65c99ca2-7243-440c-be39-07f185e1b5e1.png)

[Graduation Banner](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5292%3A130207)
[Section Complete Icon](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5193%3A128072)
![image](https://user-images.githubusercontent.com/62653834/134411313-601a608d-aaa3-45a9-9b65-7ea43341ca95.png)

#### Acceptance Criteria - Design
**Given** User has completed all tasks necessary for graduation within a specific Section (necessary tasks TBD @Jesslax)
**When** the status of the last of those necessary tasks has been changed to "complete"
**Then** a Graduation Snackbar appears at the top of their screen

**Given** A user has successfully completed all tasks necessary for graduation
**When** the user navigates to the roadmap homepage for the first time
**Then** a Graduation modal appears, the "completed" sections are collapsed and with their icons replaced by "Section Complete" icons, and they are proceeded by a Graduation Banner followed by the next section (accordion open)

**Comment by Jesslax** [comment]
@carye3  when the graduation appears, do we need all three alerts -- 1)the task completed banner, 2)you did banner, and 3)the you did it pop up--wonder if overwhelming/redundant. Could we only do one? My suggestion is the "you did it" pop up.
