### ISSUE TITLE
As Poppy, I need to see an additional Step for "Create a Business Plan"

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#45]
@aloverso @guy-nj The items in business plan and the due diligence section are adding contextual information for research, I wonder if the business owner would prefer to have a little + symbol and have more of the contextual information show below each task like "executive summary" rather than change screens to another paragraph

Activities include:

- [ ]

**Comment by skeeJay** [comment]
@Jesslax This looks like it's ready for QA from your perspective.

**Comment by Jesslax** [comment]
@skeeJay Ready!

**Comment by aloverso** [comment]
@Jesslax your comment in the description sounds like something to be researched/iterated for future stories. can we mark this one as complete?

**Comment by Jesslax** [comment]
@aloverso Fair point, should we make another user story? Or what's the best way to capture that?

**Comment by aloverso** [comment]
It sounds like something that would be a new user interaction pattern? I'd assume it'd have to go through a whole design cycle with @guy-nj to research and determine if value and how to do it
