### ISSUE TITLE
Add animation and shorten duration to snack bar

### ISSUE THREAD

**Issue by FarazA22** [newjersey/business.nj.gov#455]
As Poppy,
I need to see a snack bar with an animation as it appears on the screen and disappears within a reasonable timeframe,
So that I can see a smooth transition when the component appears on the screen and it disappears within a reasonable time (current duration is too long).

## Acceptance criteria

- [x] Snack bar should have an animation (open and close)
- [x] The length of time the snack bar appears on the screen needs to be adjusted.

## Notes
- Create an animation where the snack bar fades into/ out of position and one without the fade effect. EJ/Cary to provide feedback on preferred experience. 
- Duration needs to be shorted (perhaps some where between 3-3.5 seconds)

**Comment by FarazA22** [comment]
@skeeJay @carye3 We've added a slide transition to the snack bar and decreased the duration to 3 seconds. 

Grow and Fade are the other two options in Material-UI. Grow the was default/ already implemented. Fade is fairly close to the Grow. https://mui.com/components/snackbars/#change-transition

**Comment by skeeJay** [comment]
@carye3 should take a look as well. I actually think the "slide in" looks and feels really good, but the "slide out by going back up" feels unnecessary and distracting, and I am wondering if it should just fade out as before. You'd get the movement to draw your eye when it appears, but it'd be subtle and not distracting when it disappears… best of both worlds.

**Comment by skeeJay** [comment]
@carye3 Just a ping, want to get your opinion on the above proposal.

**Comment by carye3** [comment]
@skeeJay agree -- just need to draw the eye upon entry into screen, then fade. Beaut!

**Comment by skeeJay** [comment]
Okay so @FarazA22 I think we want to adjust the animate out back to a simple fade out.

**Comment by FarazA22** [comment]
@skeeJay Switched the transition back to the default (Grow)

**Comment by FarazA22** [comment]
@skeeJay I've made the change.

**Comment by skeeJay** [comment]
@FarazA22 Sorry, don't think I was clear: we want it to _slide_ in but _fade_ out. Does that make sense?

**Comment by FarazA22** [comment]
@skeeJay Adding an animation that slides in (Slide Animation) on entry and fades out (Grow Animation) on exit will require some time for research and custom logic to create the combo animation. Material UI doesn't support the use of multiple animations out of the box. 

Would you be comfortable picking one of the three animation options for the snack bar?
If we want the custom animation, I'd suggest we create a separate ticket and place it on the backlog. It feels like a low priority ticket when compared to other tickets this sprint.

**Comment by skeeJay** [comment]
Hmm. Okay, sounds like it would be a new user story. We'll write a new user story for it. Let's deploy with Grow, like you have it right now.
