### ISSUE TITLE
Change dev/staging myNJ self-reg to new URL

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#459]
blocked on firewall fix with IPs

- [x] change MYNJ_SERVICE_URL_DEV
- [x] change MYNJ_SERVICE_URL_STAGING
- [x] remove cert code
- [x] remove cert from AWS
- [x] remove cert secrets from github

**Comment by dsueltenfuss** [comment]
Remaining tasks will be handled with #133
