### ISSUE TITLE
Update "Back to Roadmap" button design

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#469]
[Design](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5106%3A118932)

![image](https://user-images.githubusercontent.com/62653834/133841449-794f607b-38d2-4121-97af-3d6c4eee5202.png)

**Comment by skeeJay** [comment]
LGTM
