### ISSUE TITLE
Add "Retail" industry

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#472]
Copy "Generic" Roadmap.

**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by aloverso** [comment]
@Jesslax should we show the "home-based business" question for this industry? or do we assume they are not home-based?

**Comment by Jesslax** [comment]
@aloverso great question! I need to check with Don on this. My first thought is to leave it in.

**Comment by aloverso** [comment]
Ready for QA - if you want to change the tex that displays in the onboarding dropdown, or the order, that's this file here: https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/IndustryLookup.ts
