### ISSUE TITLE
Remember which Steps are toggled open on mini-Roadmap

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#498]
**As** poppy
**I need to** have a business roadmap that is customizable (read: step accordion states are remembered) 
**So that** my Navigator workflow is personalized to my business' needs.

## Acceptance criteria

**Given** I am in a task page and have toggled the arrow button for a Step to be open
**When** I come back to the page later
**Then** the application remembers, and keeps that step open

## Notes

- [ ]

**Comment by aloverso** [comment]
@carye3 to fill in the outcome/need being filled by this story

**Comment by aaronvux** [comment]
This looks good.  Moving to staging.
