### ISSUE TITLE
Design/Research: Operate Section (2nd Iteration) "smarter" second-generation Operate Section with that integrates with Taxation data

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#528]
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by skeeJay** [comment]
@kmelefsky Can we close this? This was the design done in sprint 21 for #577.
