### ISSUE TITLE
Operate Section (V2): Entity ID input, validate EID, and present Calendar with all of a business' tax filings plus annual report

### ISSUE THREAD

**Issue by aaronvux** [newjersey/business.nj.gov#577]
As Poppy, I need the ability to input my Entity ID and display the Calendar in the Operate section of the Navigator in order to match my Tax records and return the appropriate information so I know when my filings are due.

## Acceptance criteria

**Entity ID Input Section**
- Title: Enter Your Entity ID
- Description: See design
  - Link to contextual information sidebar
- Entity ID Label
  - Link to Learn More (new window)
- Numeric Input Field
- Submit Button
  - Clicking submit calls the dummy data simulating a call to the Treasury department database
  - 0000000000 successful validation (exists, registered for taxes, full tax calendar)
  - 1111111111 successful validations (exists, registered for taxes, four tax filings)
  - 2222222222, successful Entity ID exists, NOT registered for taxes
  - All other numbers do not pass Entity ID exists validation
- Pass Entity ID from Profile if it exists with auto-submit once the operate section is opened for the first time.
- If Entity ID is successfully validated, update the Entity ID in the Profile.
- If any change is made to the Entity ID in the Profile, wipe any existing tax data. 
- Follow Design

**Entity ID Validation**
- Once submit button is clicked, highlight the field.
- Field cannot be blank
- Field only accepts numeric characters up to 10 digits.
- Follow Design

**Entity ID Does Not Exist Validation**
- Check that the Entity ID exists before checking the Entity ID is registered for taxes.
- Display Your Entity ID Does Not Exist when the Entity ID is not found in the Entity ID 
- Title: Your Entity ID Does Not Exist
- Copy Line 1: If you haven't created your Entity ID, please Create Your Entity ID here.
- Link to Create Entity ID page in a new window.

**Entity ID Is Not Registered for Taxes Validation**
- Display Registration Validation when the Entity ID is not found in the Treasury Database
- Hide Entity ID field
- Title: You aren't registered for State Taxes
- Copy Line 1: Looks like you haven't Registered for State Taxes. Once you register, we can let you know of upcoming deadlines.
- Link to Register to State Taxes in new window
- Follow Design

**Successful Entity ID Match**
- Display My Filing Calendar in the operate section
- Content: See design
- Contextual Link: What if I don't pay my taxes on time?
- Contextual Link: What happens if I don't submit my annual filings
- Calendar Title: My Filing Calendar
- Display Calendar with current month highlighted and next 11 months.
- Populate each month with the appropriate tax filing Due Date and Title
- Follow Design

## Feature Flag
- Maintain Operate section feature flag.

## Notes

- [ ] UX Review
- [ ] PO Approval

## Designs

[Entity ID Prompt](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5565%3A125442)
![image](https://user-images.githubusercontent.com/62653834/136270708-b437f799-6948-44b2-b5a0-b3518b6eb58b.png)

[Entity ID Prompt - Error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5834%3A106132)
![image](https://user-images.githubusercontent.com/62653834/138745318-a4d852fc-b9ca-4fd2-9c38-1f8b0061f96b.png)

[Entity ID Submit Success, Error: Not Registered for Taxes](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5300%3A131977)
![image](https://user-images.githubusercontent.com/62653834/136270763-53fd4c9f-d8d3-47cc-bbca-0f15edf1aaa7.png)

[Filing Calendar](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5565%3A126131)
![image](https://user-images.githubusercontent.com/62653834/136271081-56c8a3ae-6483-4394-ab3d-cc736152f04e.png)

**Comment by carye3** [comment]
@aaronvux Tooltip for My Filing Calendar: https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=5572%3A126661

**Comment by aloverso** [comment]
@carye3 to clarify the situation where you get the "you aren't registered for state taxes" error - 
1. you want us to hide the text input field for that error? (but not for the "not found" error)?
2. if so, where does the "here" link go to?

**Comment by aloverso** [comment]
To me, it seems a bit strange to hide the text field for one error message but not the other. Especially since the error text says "entered the wrong Entity ID? Change it here" - because it doesn't actually show what entity ID I entered, so I'd have to scroll back up the page to even see if my entity ID is correct or not. And then scroll back down to click the "here" link. Why not just keep the editable text field there on the screen?

**Comment by carye3** [comment]
Good point @aloverso let's keep the text entry for both. I'll update the designs

**Comment by aaronvux** [comment]
@aloverso this looks pretty good. It looks like we are missing the blank field validation on the entity ID input field on the Operate section.  In mobile (chrome), if I submit with no value, then type a character, nothing appears in the box, but then the next character does appear.   @carye3 the filings calendar is only showing the annual report filing, in the design we are showing the additional filings.  Did we want to mock both or does it matter?

**Comment by aaronvux** [comment]
@carye3 @fiorella-io We probably need to show a success message when both validations pass for the Entity ID.  Also, there's no way for me to edit my Entity ID from the operate section.  The user needs to know to go to the Profile section.  If they input the Entity ID from the Profile section without going to Operate, there's no indication of how the information was pulled.

**Comment by aaronvux** [comment]
@Jesslax Do we want to take the user straight to the NJ.gov pages for tax registration and creating an Entity ID?  Currently, we are taking them to the corresponding task page.

**Comment by Jesslax** [comment]
@aloverso I have a sketch out of other filing types: https://docs.google.com/spreadsheets/d/1FY8H4XGeqZDNKeAmBrB8eonMarySCrkuJRu8Y61iM8A/edit?usp=sharing. But the copy hasn't been edited yet. It's a lot of copy paste. 

@aaronvux Not sure I follow? Are you talking about tasks in step 3?

**Comment by aaronvux** [comment]
@Jesslax when the error validations come up for not being registered for taxes and not having an entity ID, there are links in the error message.  They take the user to the the corresponding task in the Navigator.  Is that expected or should we send them directly to the NJ sites to register and get their entity ID?

**Comment by Jesslax** [comment]
@aaronvux I like the idea of taking them to the task screen-as it currently shows. We are building this so I can change copy though, right?

**Comment by aaronvux** [comment]
@aloverso thanks for the validation fix.  @carye3 @fiorella-io please review.

**Comment by aloverso** [comment]
@Jesslax yes the copy can all be changed

**Comment by carye3** [comment]
lgtm. i'm guessing its supposed to display annual report multiple times? 
![image](https://user-images.githubusercontent.com/62653834/140991588-d1521eed-3134-4794-aa08-1a4c4ae86b30.png)

**Comment by aloverso** [comment]
@carye3 yeah, the acceptance criteria said to show a "full" calendar for one ID, and four for another, but we don't have any filings written into the app other than Annual Report so that's all that I can show
