### ISSUE TITLE
As Poppy, I don't want anyone else to view or edit my data

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#61]
Only the authenticated user should be able to get or edit that user's data

on backend api:
- [x]  validate that JWT token user is the same as the requested userId info

serverless backend setup
- [x]  validate JWT token against cognito pool

**Comment by aloverso** [comment]
some dev resources:
https://itnext.io/aws-cognito-example-using-react-ui-and-node-js-rest-apis-part-3-jwt-secured-rest-apis-e56d336ce306
https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers

**Comment by aloverso** [comment]
@skeeJay Do you want me to show you how I tested this, for QA purposes? It's dev-centric but it is testable by anyone as long as you know how

**Comment by skeeJay** [comment]
This looks good to the extent I was able to test it. We'll keep an eye on it to see if we discovery any workarounds, but for now marking as Ready to Deploy.
