### ISSUE TITLE
As Poppy, I need to be redirected directly to my roadmap page if I go to the "root" url and I'm already signed in

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#65]
Activities include:

- [ ]

**Comment by skeeJay** [comment]
@aloverso Yes, now I see the flash, exactly as you described it :) I think that works perfectly well for now, while we're we're doing internal development. It does make me wonder how a production application (e.g., facebook.com) would avoid that, taking a logged in user directly to a logged-in experience, without affecting the SEO of the original landing page.

**Comment by skeeJay** [comment]
@aloverso Just curious about this comparison with other production websites (like facebook.com) before I close this out. Curious if that is the kind of situation that would take considerably more engineering as a later user story before going public, to both maintain SEO and bring users "right" to the logged-in experience.

**Comment by aloverso** [comment]
I did a bit of looking and I think facebook makes the opposite choice from us - they appear to choose the "don't flicker the page with the drawback of worse SEO" option.

This is the facebook landing page when you're not signed in:
![image](https://user-images.githubusercontent.com/6563663/111492685-45328800-8713-11eb-8b11-f35bbe31f72a.png)

Searching "facebook" on google of course takes me here, but if I actually look for the content shown on this page, like "Create a Page for a celebrity, band or business." or "Connect with friends and the world around you" then this page it doesn't show up in google search results

![image](https://user-images.githubusercontent.com/6563663/111493119-a65a5b80-8713-11eb-892f-e6b7d2afe3c2.png)

![image](https://user-images.githubusercontent.com/6563663/111493173-b1ad8700-8713-11eb-9fe0-73160d8705d6.png)

**Comment by skeeJay** [comment]
@aloverso I see. In that case I wonder if we maybe should go in the other direction as well: to maximize user experience, at the expense of SEO, which I suppose we would just do the best we can with, the way Facebook does. At any rate, I assume it's a user story for a future sprint, yes?

**Comment by aloverso** [comment]
@skeeJay Yes, let's make it a future user story if we want to change it. I'm not sure what the best answer for us is, but I would suggest staying with what we have for the time being, I guess? Facebook doesn't really *need* SEO because they're a household name, and we will probably have more content on the landing page than they do

**Comment by skeeJay** [comment]
@aloverso Yes. There's another alternative, which is to retain the "flash" of the landing page but make the redirect more pleasant/intentional so it doesn't look like a glitch… a nice animation, a spinner, or a little "logging you back in" heads-up modal pops up, or something.
