### ISSUE TITLE
Content: Add more information on LP and LLP to Business.NJ.gov

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#693]
## Tasks:

- [ ] Research and create more information on LP and LLPs, similar to what has been created for other legal structures.
https://business.nj.gov/pages/choose-a-business-structure
- [ ] Add the link to the more information to the Navigator's onboarding page. https://github.com/newjersey/business.nj.gov/blob/main/web/display-content/onboarding/legal-structure/limited-liability-partnership.md

**Comment by CeciliaRam** [comment]
@Jesslax draft ready for review
https://docs.google.com/document/d/1bOygF_85kZaQ8zjkMBLfBsDFOwjcda1-6NR1Y3pk2W4/edit#
