### ISSUE TITLE
Determine minimum criteria for public beta

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#72]
Activities include:

- [ ] Subdomain, e.g., dashboard.business.nj.gov
- [ ] User authentication/myNJ
- [ ] Production servers
- [ ] Load testing

**Comment by aloverso** [comment]
Tracking here: https://docs.google.com/spreadsheets/d/14noM3NXceXGQ73lxyJdTfHzzUBELMoND-VIr3ppM7AQ/edit?usp=sharing
