### ISSUE TITLE
Jess and Ce: Discuss CMS needs

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#730]
https://docs.google.com/document/d/1KrelOapC0C2hl-dHMnVvJadqy8nuQ4tls3x79iFxYo4/edit?usp=sharing

## Tasks

- [ ] Draft high level requirements
- [ ] Task out what we want to do

**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by Jesslax** [comment]
@aaronvux should we close this tkt? what else do C and I need to do here?

**Comment by aaronvux** [comment]
Closing
