### ISSUE TITLE
Content: Newsletter and User Research Opt-Out Functionality in Login

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#749]
**As** <PERSONA>
**I need to** be able to opt out of Newsletter
**So that** I can control the amount of information I receive

## Acceptance criteria

**Given** <CONDITION>
**When** <ACTION>
**Then** <OUTCOME>

## Notes

- [ ]

**Comment by Jesslax** [comment]
Created #925 and #926 on sprint board
