### ISSUE TITLE
Profile: Inline Location Entry Error Notification with Snackbar

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#764]
**As a** general user
**I need to** have a consistent experience
**In order to** use the tool with ease and minimal errors.

Consistent with in-line text field entry error message, accompanied by snackbar

## Acceptance Criteria

- Profile Page:
   - If format validation fails, on blur display inline error message below a red boundary
     - Error message: "This location is invalid. Please select one from the dropdown menu."
   - If the user attempts to save their changes, display error snackbar
 - Onboarding
   -  If format validation fails, on blur display inline error message below a red boundary
      - Error message: "This location is invalid. Please select one from the dropdown menu."
   -  If the user attempts to click "Next", display error snackbar

## Design

[Profile Page / Location error border, text and snackbar](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5763%3A107348)
![image](https://user-images.githubusercontent.com/62653834/139305157-3daf3140-52b9-42d7-82fe-701391ed7754.png)

[Onboarding/Location error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5906%3A106847)
![image](https://user-images.githubusercontent.com/62653834/139314868-b2a75943-a74f-4978-8dd9-10f4872b5fb4.png)

**Comment by mikewolfd** [comment]
Can you upgrade the acceptance criteria to include inline notifications for legal standing in onboarding, as it uses the same kind of logic

**Comment by aaronvux** [comment]
@mikewolfd not seeing the inline error on the location field.
<img width="1099" alt="Screen Shot 2021-11-03 at 10 23 48 AM" src="https://user-images.githubusercontent.com/36163601/140078805-b1236a07-ace2-45c8-affe-fac9183a7ae9.png">

**Comment by aaronvux** [comment]
@mikewolfd @carye3 should it say "Error" in the field.  I would think the field would just be blank
<img width="820" alt="Screen Shot 2021-11-04 at 11 14 07 AM" src="https://user-images.githubusercontent.com/36163601/140344263-d9a228b4-4517-45ee-af22-f557651d9107.png">
.

**Comment by mikewolfd** [comment]
It wasn't in the design? And all the fields in the profile shows that field text

**Comment by carye3** [comment]
No it shouldn't say error in the field or have red text (see screenshots above) @aaronvux @mikewolfd. Text in the field should either contain the placeholder text prior to user entry or whatever the user had entered

**Comment by mikewolfd** [comment]
Can we create a new ticket for that?

**Comment by aaronvux** [comment]
Let's talk about this at standup tomorrow. @kmelefsky

**Comment by aaronvux** [comment]
Remove Error text.  Leave place holder text if blank or user entered value that caused the error.

**Comment by aloverso** [comment]
@aaronvux @carye3 ready for re-review

**Comment by aaronvux** [comment]
Looks good to me.  @carye3 let me know if we are good to move it please.

**Comment by carye3** [comment]
lgtm
