### ISSUE TITLE
As Poppy, I need to see the input flow steps and visuals as defined by requirements and design, respectively

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#77]
**Design Prototype**
[Laptop mock](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1034%3A228&viewport=-1611%2C591%2C0.2630005180835724&scaling=min-zoom&page-id=633%3A6362)
[Mobile mock (with animation)](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1034%3A506&viewport=-1611%2C591%2C0.2630005180835724&scaling=min-zoom&page-id=633%3A6362)

**Design**
[Laptop](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1034%3A228)
https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=1034%3A583

**User Actions**
As a user, 
1. I see the the content of the Step 1 slide and fade in from the right side. @aloverso and @guy-nj to discuss animation style
2. I don't see "Back" button in the step 1.
3. I see a 48px spacing between the page content and CTA section.
4. When I click "Next", the current step fades and moves out to the left side of my screen, and the next step fades and moves in from the right side. 
5. When I click "Back", the current step moves and fades out to the right side of my screen, and the previous step fades and moves in from the left side.
6. I see the "Next" button is always activated. If I click "Next" without completing required fields, I see error messages next to fields explaining I have to complete them in order to move on to the next step. 
7. Error message: @aloverso and @guy-nj to discuss

Dev checklist

- [x] look and feel of page
- [x] simplify the userData object
- [x] page animations
- [x] mobile

**Comment by aloverso** [comment]
@skeeJay @guy-nj Reading through this again, I think error messages should be a separate story? That sounds like new behavior that is separate from the new visual design / flow through the onboarding. If we track it separately, we can spend more time diving into what those should look like without blocking the acceptance of this story

**Comment by skeeJay** [comment]
@aloverso That sounds correct to me.

**Comment by skeeJay** [comment]
Well that's a very clean onboarding process. Just to confirm, so everyone is on the same page: looks like industry selection and legal structure are simple dropdowns so far, which will be upgraded via user stories in future sprints, and municipality selection is a new screen that will be added via future sprint. So the paradigm of walking through onboarding is there, but several of the individual screens will still be upgraded.

I think this will require QA by both Guy and Jess.

@Jesslax With the caveat that the industry, legal entity, and municipality selection are being upgraded in the future, can you take a look at what is being asked now and make sure it is correct-ish for the time being, with a special emphasis on naming your business, which we have no further plans for? Are the "two" different explanatory paragraphs of different font sizes the intended descriptive information?

@guy-nj You should look at this from a design perspective as well. One thing to raise: when typing in the name of your business, the input field text font size is small, smaller even than the introductory text paragraph font size. Would it be better if this input field were bigger, say, on par with the input field/dropdown hybrids you have been designing? The user might feel more "powerful" if typing their business name in a bigger font size, particularly since it's the only input field on the whole screen.

**Comment by Jesslax** [comment]
@aloverso Can you remove all text before "Business Name" please.

**Comment by aloverso** [comment]
@Jesslax should be all set, let me know if we can close :)
