### ISSUE TITLE
Display "not entered" fields in Mini-Profile

### ISSUE THREAD

**Issue by carye3** [newjersey/business.nj.gov#789]
As Poppy/Oscar, I need to see what business information (eg EIN, Entity ID) is missing from my business profile in order to understand if I've gathered all relevant information to have a fully functional personalized business roadmap experience.

## Acceptance Criteria

- In mini roadmap (expanded), always display Notes field; if that data is missing, then display text "not entered" (see design)
- In mini roadmap (expanded), depending on legal structure always display EIN, Entity ID, Tax Registration; if that data is missing, display text "not entered" (see design)
- In mini roadmap (expanded), always display Business Name, Industry, Legal Entity, Location; if that data is missing, then display text "not set"
- On desktop, the # of lines of text on the right hand column should never exceed the # of lines of text on the left.

## Design

[Desktop](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5795%3A104363)

[Mobile: Collapsed](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5795%3A103583)
[Mobile: Expanded](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5795%3A103367)

![image](https://user-images.githubusercontent.com/62653834/138090422-0c821d7c-02e5-46cc-8a1f-eead13535f2a.png)
![image](https://user-images.githubusercontent.com/62653834/138090523-a01f6b3f-4efb-4427-843f-09599179f854.png)

**Comment by FarazA22** [comment]
@aaronvux  @carye3 
I have two comments:
1) The Legal Entity and Location are required fields during onboarding. I've added logic to display text "not entered" when the profile data is missing. But do we need the logic/ AC? We would never run into this scenario.

2) We are no longer displaying the business name. This field is not required during onboarding. If the user did not set/enter a business name, do we want to display 'business name: not entered/ not set'? Note: with this removal, we moved EIN from the right column to the left. If the business name is dynamically rendering, I need a decision on the placement of the EIN.

Let me know if either of theses are scoped out to another ticket.

**Comment by aaronvux** [comment]
Let me talk to Cary about this one.  There is a reason why certain thing display and others don't.  I'll get back to you shortly.

**Comment by carye3** [comment]
thx @FarazA22 I attached the wrong design; attached designs from Mini roadmap ticket this was based on

1. There might be a scenario where we run into this issue, so thx for creating logic
2. I've updated acceptance criteria to say that on desktop the # of lines of text on the right hand column should never exceed the # of lines of text on the left.

**Comment by FarazA22** [comment]
@carye3 When we are displaying 'not entered' and 'not set' text, are we using text-bold and italics text style applied to the font? The updated designs do not show the 'data not available' state.

**Comment by carye3** [comment]
@FarazA22 yes and please apply the same design to "data not available" -- ty!

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
This looks good.  @carye3 please review.

**Comment by aaronvux** [comment]
@carye3 please check this so it can be moved if ready.

**Comment by carye3** [comment]
perf! @aaronvux lgtm
