### ISSUE TITLE
Content: Copy review for new features going live

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#793]
## Tasks:

- [ ]

**Comment by Jesslax** [comment]
@skeeJay was this for the copy we launched on the site today?

**Comment by skeeJay** [comment]
@Jesslax This was meant to be a placeholder for all review work you need to do over the course of a sprint, so that we filled the sprint appropriately. Roadmaps, etc. But I figure you can use this ticket as you see fit for representing all that work.
