### ISSUE TITLE
Human-readable industry text on roadmap page

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#80]
**Current Behavior:**

Seeing code-readable industry instead of human-readable industry

For example: `home-contractor`

![Screen Shot 2021-04-01 at 2 33 07 PM](https://user-images.githubusercontent.com/6563663/113338508-35ac6500-92f7-11eb-8cbe-c1102fdd44bf.png)

**Expected Behavior:**

Should see human version that matches the onboarding form `Home-Improvement Contractor`

**Steps to Reproduce:**
1. Enter home contractor in onboarding flow
2. See the wrong text in the grey box on the roadmap page

**Comment by skeeJay** [comment]
@aloverso I know we are still discussing the precise terminology of the generic roadmap, and this is one of the places that various variants would appear. Is it easy to edit "Not set" down the road?
