### ISSUE TITLE
In the dropdown, the popup menu should line up with the original dropdown field

### ISSUE THREAD

**Issue by guy-nj** [newjersey/business.nj.gov#81]
As a user, when I click a dropdown field, the selected item in the popup menu should be lined up with the selected item in the default dropdown field.

This ticket is related to [the Status dropdown on the Task page](https://github.com/newjersey/business.nj.gov/issues/32). When the task is marked as "Completed", if I click the Status dropdown,  the popup menu should be moved up so its "Completed" lines up with "Completed" in the default field. Currently the popup menu is fixed position and my cursor is on "Not Started" when the popup menu appears.

Please take the Simple Select component in Material UI as reference: https://material-ui.com/components/selects/

@aloverso feel free to edit the description. @skeeJay for the awareness.

**Comment by skeeJay** [comment]
@guy-nj Can you QA?

**Comment by guy-nj** [comment]
@aloverso The vertical alignment looks good. Can we also make them horizontally aligned too? Let me know if there is any concern.

**Comment by skeeJay** [comment]
@guy-nj Please just make sure to add the "needs work" label when you QA and send back to @aloverso.

**Comment by guy-nj** [comment]
@aloverso @skeeJay It looks good. Thanks!
