### ISSUE TITLE
Screen reader reads drop down menu selection on Onboarding page 2

### ISSUE THREAD

**Issue by FarazA22** [newjersey/business.nj.gov#815]
After the accessibility user selects an industry from the menu list (onboarding page 2 drop down), the screen reader states the selection that was made when the menu list closes. The selected industry is also read when the user navigates to the drop down menu.

**Comment by FarazA22** [comment]
@aaronvux Ready for review

**Comment by aaronvux** [comment]
this is good.  Moving to staging.
