### ISSUE TITLE
Spec for municipal requirements task screen

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#82]
Activities include:

- [ ]

**Comment by dltinnovate** [comment]
Roadmap: Step 4 Task 2

Activities Include:

1.  [Display instructions and content for users]
   - Description Text
   - Will Need
   - Will Get
2. [Display the town selected during onboarding]
3. [Link Users to the local municipal website of the town they selected during onboarding]

[This document ](https://docs.google.com/document/d/1pXNg4Zndd1EuWYfUv9ep38CTSYTozIvwJipSkiT_yrY/edit?usp=sharing) contains the Task Screen, Roadmap View, all text, and Potential Contextual Information.

[Airtable with list of Municipalities and their Websites](https://airtable.com/invite/l?inviteId=invBOQXzyIMg9K6Mm&inviteToken=b2f62f141c99f445876c36aa0b4cd3384abcd5bc70e1feee1d514d5a226c9ba6)

**Comment by skeeJay** [comment]
@dltinnovate Thanks Joe. Could you actually attach these materials to #25 by editing the description of that user story? Thanks!

**Comment by dltinnovate** [comment]
> @dltinnovate Thanks Joe. Could you actually attach these materials to #25 by editing the description of that user story? Thanks!

It looks like I don't have permission. Added it to the comment there for the time being.
