### ISSUE TITLE
Create Navigator Banner on the Top of the Register page

### ISSUE THREAD

**Issue by aaronvux** [newjersey/business.nj.gov#821]
As a biz.nj user, I need the ability to access the Navigator from the Register page on biz.nj so that I can leverage the Navigator functionality to support my business. 

## Acceptance criteria

- Create Navigator Banner on Top of the Register page with button.

## Notes

@carye3 please attach the design.

**Comment by dltinnovate** [comment]
created, pending final review by @Jesslax

**Comment by dltinnovate** [comment]
Now live. https://business.nj.gov/pages/register-your-business
