### ISSUE TITLE
As Poppy, I need to see contextual information for terms I don't understand on the input flow or task screens

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#84]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=633%3A6362&node-id=1632%3A19859&viewport=198%2C-873%2C0.3714682459831238&scaling=min-zoom)
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=633%3A6362&node-id=1654%3A0&viewport=-413%2C-1078%2C0.40014758706092834&scaling=min-zoom)

**User Actions**
As Poppy (or any user):
1. I see 2px-thick dot-lines underneath the terms that I might need more explanation to udnerstand. The dotlines look different from the regular link with a solid underline.
2. The dotline's hover style is the same as regular link's hover style.
3. After clicking, a box with contextual information appears on the right side of the screen.
4. Inside the information box, I can tell the external links with a link-out icon which will open a new window to show me more information.
5.  Inside the information box, I can also see dotlines underneath some terms. After clicking one of those, the contextual information for the term will replace the current content in the information box.
6. I can click outside the information box, or "X" on the top right corner to exit/close the box.
7. The information box sides in when opening and sides out when closing. @aloverso to discuss the animation details.

**Review Items**
- [x] Cursor does not change to pointer when you mouseover linked term.
- [x] Cursor does not change to pointer when you mouseover the "X" close button in sidebar.
- [x] You should be able to click outside the sidebar to close it.
- [x] Text-decoration-style should be dashed instead of dotted line.
- [x] When the browser width changes to <640, panel should be 75% wide
- [x] The padding in the box should be 24px. 
![contextual-info-padding24](https://user-images.githubusercontent.com/77984966/116258172-b6b61b00-a742-11eb-9328-40a222056c06.png)

**Comment by skeeJay** [comment]
Sorry, thought I commented on this yesterday. @guy-nj @Jesslax this one might need QA from both of you, from a design-perspective and in terms of whether it accomplishes our contextual information goals, respectively.

**Comment by Jesslax** [comment]
@skeeJay I still think a back button within the tool tip would be helpful. Otherwise looks good. The text needs to be updated of course. I know I'll have time for that in the coming weeks.

**Comment by skeeJay** [comment]
Added a couple of design notes to description to start QA, but I will continue and @guy-nj will take a look and add as needed.

**Comment by aloverso** [comment]
@skeeJay re the comments on the green underline, I was going based on @guy-nj 's design notes that it should be 2px - not sure if he was measuring something else than the way the browser measures, but it's currently 2px right now 
![image](https://user-images.githubusercontent.com/6563663/115924158-5cb90b00-a44d-11eb-90a1-327705962313.png)

**Comment by skeeJay** [comment]
@aloverso Rog that, will defer to @guy-nj

**Comment by aloverso** [comment]
@guy-nj I'm unsure what's meant by the "jumping into a small size" review item, can you elaborate? thanks!

**Comment by guy-nj** [comment]
I meant the bluebox weirdly switches to a very narrow width. Do you know how the width is calculated when <640?

**Comment by aloverso** [comment]
Ah, okay. Yes, at 640px (40em) screen width, the sidebar switches from 30em wide to 20em wide.

20em is the width of the mobile sidenav (for the mini-roadmap) so I assumed we wanted those sizes to be consistent for small screens. For example, [on a task page](https://dev.d3v9e9ms5ulsh2.amplifyapp.com/tasks/register-for-ein) at smaller screen-size, the two side-menus are symmetrically the same width. Could change that if you like.

It switches at 640px because the next breakpoint option is 480px (30em). If we switched there, then a 481px screen would still have a 30em (480px)-wide contextual info menu, taking up pretty much the entire screen.

**Comment by guy-nj** [comment]
Per dashed line style, we will use the default CSS style instead of customizing it to match the design.

**Comment by skeeJay** [comment]
@guy-nj Just to play devil's advocate: didn't you learn from user testing that the default dashed line style was not being noticed by users? I know it should be rare and very strongly justified to override a web standard, but I'm wondering if this would be a case for it if we know that the feature becomes mostly not noticed/pointless according when following this standard?

**Comment by aloverso** [comment]
here's a few screenshots:

## using default browser-underline behavior (for 2px thickness and for distance from text)

![Screen Shot 2021-04-26 at 11 45 42 AM](https://user-images.githubusercontent.com/6563663/116113000-1995ac80-a686-11eb-89fa-dc6659721f4a.png)
![Screen Shot 2021-04-26 at 11 45 30 AM](https://user-images.githubusercontent.com/6563663/116113021-1dc1ca00-a686-11eb-9b04-95eb2384d25a.png)


## using border-bottom 2px as underline instead of "browser" underline:
![Screen Shot 2021-04-26 at 11 46 54 AM](https://user-images.githubusercontent.com/6563663/116113052-24504180-a686-11eb-87bd-b6952d5e2057.png)
![Screen Shot 2021-04-26 at 11 47 54 AM](https://user-images.githubusercontent.com/6563663/116113061-26b29b80-a686-11eb-97c6-d780ead3d86a.png)


## using border-bottom 3px as underline instead of "browser" underline:
![Screen Shot 2021-04-26 at 11 48 02 AM](https://user-images.githubusercontent.com/6563663/116113110-2e724000-a686-11eb-8114-8970fc265d2f.png)
![Screen Shot 2021-04-26 at 11 48 08 AM](https://user-images.githubusercontent.com/6563663/116113124-3205c700-a686-11eb-9e63-c538b275a2a2.png)

**Comment by guy-nj** [comment]
@skeeJay Sorry if i was not clear. We will keep the 2px line weight but not customizing the space & line length to how it is in the design. The 2px weight should provide enough visual prompt for a better usability.

@aloverso Thanks for the image. The 2px dashed line with 1px text distance looks good to me.

**Comment by skeeJay** [comment]
Got it. If we are using border-bottom 2px dashed line with 1px text distance, with the "long dash" variant that @aloverso shows in this screenshot, that looks strong and noticeable to me.

**Comment by guy-nj** [comment]
I missed one thing. Can we fix the padding in the box to 24px? I have added this to the checklist in the story.

**Comment by aloverso** [comment]
@guy-nj can we schedule that design/dev pairing meeting to cover this and any other small changes? this seems like a great candidate for a "small fixes we can go through together" list for us to cover at a meeting like that

**Comment by guy-nj** [comment]
Let's do that.

**Comment by Jesslax** [comment]
@skeeJay Continue to think a back button would be helpful, but if not worth it for MVP, that's fine.
@guy-nj @skeeJay I wonder if the text is short, say like 1-2 sentence, the blue side bar should pop up and take up less of the screen?

**Comment by guy-nj** [comment]
I tend to keep the same treatment for both long and short content just for now. Otherwise it's essentially 2 contextual info styles. That could be the research we continue in the next round interviews?

**Comment by skeeJay** [comment]
@Jesslax Both new behaviors like the back button or different sizes are the kind of things that we could discuss for future user stories, but they weren't in the design or acceptance criteria of this user story, so not really in the scope of review. We can definitely think about them for future user stories, though.

**Comment by Jesslax** [comment]
@skeeJay sounds good, should I add a new note for this?

**Comment by skeeJay** [comment]
@Jesslax Going to leave this in the review column until the review meeting scheduled for tomorrow.

As far creating new tickets, if it's something that needs design, you can create a ticket in the Drawing Board. If it's something that doesn't need design or the design is straightforward, you can write a user story in the Sprint Planning board.

We'll need to be more rigorous in our prioritization meetings going forward to start to surface and prioritize this new tickets. Folks should maybe come into the meeting having reviewed the backlog and with a top priority to highlight.

**Comment by skeeJay** [comment]
Two questions in advance of our discussion today:

1. Some sidebars have titles, and some don't. Is that intentional?
2. Why does the X have a green outline?

**Comment by aloverso** [comment]
@skeeJay:

1. The content of the sidebars is fully editable, including whether there are headers and any other styling. I was just going off the "placeholder" content in the designs, so I expect it'll get changed going forwards
2. The green outline on the X is the "focused" element. On any page, if you start using your keyboard to tab and navigate through elements, you'll notice the same green box outlining the focused element. It's necessary when opening a pop-up window like a sidebar to "focus" an element within it, which makes the sidebar accessible by keyboard users.

**Comment by skeeJay** [comment]
@aloverso Rog on both, thanks!
