### ISSUE TITLE
Make sure the roadmap vertical lines extend all the way to the next step

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#85]
**Current Behavior:**

![image](https://user-images.githubusercontent.com/6563663/113911901-849b4400-97a8-11eb-8f4e-348f549b75e9.png)

**Expected Behavior:**

line extends to roadmap step 2

**Steps to Reproduce:**
1. go to roadmap on mobile view

**Comment by skeeJay** [comment]
@guy-nj If you could take a look at this from a design perspective, that would be great, thanks.

**Comment by guy-nj** [comment]
It looks good to me.
