### ISSUE TITLE
As E.J., I need to demo from a staging server separate from the dev server

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#87]
Activities include:

- [x] create new AWS environment
- [x] update github pipeline to trigger deployments to staging
- [x] handle new staging secrets

**Comment by aloverso** [comment]
@skeeJay A few notes for reviewing this one:
- The staging site lives at this URL: https://staging.d3v9e9ms5ulsh2.amplifyapp.com/ which is also now linked on [our wiki](https://github.com/newjersey/business.nj.gov/wiki)
- It's a completely new environment, which means you will have to create a new user account here
- For any future work, things get automatically deployed to our Dev environment, and then someone needs to click a button to promote it to staging whenever we're ready. Right now, that's just me who has the permission, but we can give that power to anyone in our github team. We should just take 2 min to show how it works

**Comment by skeeJay** [comment]
LGTM
