### ISSUE TITLE
Update Tax Filing Table

### ISSUE THREAD

**Issue by aaronvux** [newjersey/business.nj.gov#927]
As poppy, I need to understand what taxes are due so I can plan and stay in compliance with NJ tax law.

## Acceptance criteria

Display Annual Taxes in Blue (see Design)
Display all other filings in Yellow (see Design)

For Entity ID: 0000000000
- Follow the Design for Content 
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6099%3A111650

<img width="811" alt="Screen Shot 2021-11-09 at 3 54 26 PM" src="https://user-images.githubusercontent.com/36163601/141003047-d0496ca1-f632-4df9-ade0-56f5ab553c28.png">

For Entity ID: 1111111111
- Follow the Design for Content 
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6103%3A111732

<img width="660" alt="Screen Shot 2021-11-09 at 3 54 39 PM" src="https://user-images.githubusercontent.com/36163601/141003076-8d1a21ad-8fa6-4511-93c6-8eeaeb527dca.png">

## Notes

Lorem Ipsum is fine for the content on the additional filing screens.

**Comment by aaronvux** [comment]
@carye3 @aloverso @skeeJay Created a separate ticket to update the tax calendar.

**Comment by aloverso** [comment]
@aaronvux ready for review. Couldn't use lorem ipsum because it made our automatic spellchecker mad, so I hope this is fine as placeholder text.

**Comment by aaronvux** [comment]
@aloverso this looks good to me.  Thank you so much!  @carye3 @skeeJay please take a look.  This is still a placeholder for now and we can update the copy as necessary for stakeholder reviews.

**Comment by skeeJay** [comment]
Cooooooool. This is looking great, I think. And set, we can adjust the titles and descriptions of the filings on the calendar as desired after going to staging, before showing to stakeholders.

@aaronvux One minor tweak/bug for a future ticket: there is a hover state on the yellow Annual Report box on the calendar, but not on any of the blue Tax Filing boxes on the calendar.
