### ISSUE TITLE
As Poppy, I need to authenticate with a myNJ account

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#95]
Activities include:

- [x] set up cognito SAML with metadata from myNJ folks
- [x] send the AWS-generated metadata back to myNJ folks
- [x] set up a webservice to handle self-reg
- [x] set up attribute mapping for the fields we care about (email and myNJ auth id)

Dev tasks

backend
- [x] finish test for xml response body parsing (grant AND resume)
- [x] fix text for uuidv4 stuff
- [x] change backend to expect name in request, send to mynj

frontend
- [x] field to collect name, send to backend
- [x] error message if dont match
- [x] error message if mynj fails
- [x] cant access page if already signed in
- [x] ask Guy about what url we want
- [ ] design! the page

infra
- [x] add all the mynj secrets to github
- [x] do the cert for staging 
- [ ] add staging secrets to github

other
- [ ] rename LANDING_PAGE_URL var to be REDIRECT_URL or something

**Comment by aloverso** [comment]
@skeeJay @guy-nj here's screenshots of the myNJ registration flow

![Screen Shot 2021-07-13 at 10 20 56 AM](https://user-images.githubusercontent.com/6563663/125469104-c5d3df1f-de0c-486b-a044-4036e3c8b3f7.png)

![Screen Shot 2021-07-13 at 10 21 09 AM](https://user-images.githubusercontent.com/6563663/125469118-6e05f375-0711-4b85-b651-c538619fb886.png)

![Screen Shot 2021-07-13 at 10 21 20 AM](https://user-images.githubusercontent.com/6563663/125469148-4debe763-37f2-4cb7-9d4c-0e636e3c1907.png)

![Screen Shot 2021-07-13 at 10 21 33 AM](https://user-images.githubusercontent.com/6563663/125469157-fe0c4331-9c4d-40af-a98f-7f6a55da55c9.png)

The "Continue" button at the end of this page will create your account and then redirect the user to our onboarding page

**Comment by guy-nj** [comment]
Thanks! I assume the Log In experience is the same as our current flow:

Click "Log In" on the landing page --> Type in email and password on MyNJ site --> (If success) Redirect to Dashboard


________________________________
From: Anne LoVerso ***@***.***>
Sent: Tuesday, July 13, 2021 10:24 AM
To: newjersey/business.nj.gov ***@***.***>
Cc: Lee, Guy [innovation] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [newjersey/business.nj.gov] As Poppy, I need to authenticate with a myNJ account (#95)


@skeeJay<https://urldefense.com/v3/__https://github.com/skeeJay__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf4bgKAwZ$> @guy-nj<https://urldefense.com/v3/__https://github.com/guy-nj__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf5kkULSI$> here's screenshots of the myNJ registration flow

[Screen Shot 2021-07-13 at 10 20 56 AM]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/6563663/125469104-c5d3df1f-de0c-486b-a044-4036e3c8b3f7.png__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf8bDRtUg$>

[Screen Shot 2021-07-13 at 10 21 09 AM]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/6563663/125469118-6e05f375-0711-4b85-b651-c538619fb886.png__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf9nbNkX5$>

[Screen Shot 2021-07-13 at 10 21 20 AM]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/6563663/125469148-4debe763-37f2-4cb7-9d4c-0e636e3c1907.png__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf_1calhU$>

[Screen Shot 2021-07-13 at 10 21 33 AM]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/6563663/125469157-fe0c4331-9c4d-40af-a98f-7f6a55da55c9.png__;!!J30X0ZrnC1oQtbA!a11oeCx_17COV_DjV_DEoB-qVKUvE4ZgmFKVhIog6MKIWzWOxnjwjoV9MOJAf3GIyKih$>

The "Continue" button at the end of this page will create your account and then redirect the user to our onboarding page

**Comment by aloverso** [comment]
Yep! That will stay the same as it is right now already

**Comment by guy-nj** [comment]
I found the redirect doesn't work if I failed the login in the 1st time. Then I am brought to the myNJ dashboard after I try again logged in. Please see the attached step-by-step screenshots. Will the user see "Business.nj.gov Navigator" link on the left side of the myNJ dashboard? Or can the redirect always work no matter how many times the user tries?




________________________________
From: Anne LoVerso ***@***.***>
Sent: Tuesday, July 13, 2021 2:16 PM
To: newjersey/business.nj.gov ***@***.***>
Cc: Lee, Guy [innovation] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [newjersey/business.nj.gov] As Poppy, I need to authenticate with a myNJ account (#95)


Yep! That will stay the same as it is right now already

**Comment by skeeJay** [comment]
@guy-nj See if you can take a look by EOD.

**Comment by guy-nj** [comment]
It looks good to me!
